'use strict';
function bondRank(c){const score=Math.min(c.affection||0,c.friendship||0);return score>=100?3:score>=60?2:score>=25?1:0;}
function bondSpeed(c){return 1-bondRank(c)*.02;}
function catRequest(c){if(c.dailyRequest?.day!==day()){const serial=Math.floor(now()/86400000),pool=['wheat','egg','milk','bread','perch','flower'].filter(k=>k==='wheat'||quantity(k)>0||canMake(k)),item=pool[(serial+c.id)%pool.length],count=item==='wheat'?3:1;c.dailyRequest={day:day(),item,count};saveGame();}const {item,count}=c.dailyRequest;return {item,count,done:c.requestDay===day(),coins:Math.max(10,Math.round(ITEMS[item].value*count*.5))};}
function completeCatRequest(id){const c=S.cats.find(c=>c.id===+id);if(!c)return false;const r=catRequest(c);if(r.done||!has({[r.item]:r.count}))return false;take({[r.item]:r.count});c.requestDay=day();c.affection=Math.min(100,(c.affection||0)+10);c.friendship=Math.min(100,(c.friendship||0)+8);S.coins+=r.coins;change();return true;}
function claimBond(args){const[id,tier]=args.split(',').map(Number),c=S.cats.find(c=>c.id===id);if(!c||![1,2,3].includes(tier)||bondRank(c)<tier||(c.bondClaims||[]).includes(tier))return false;c.bondClaims ||= [];c.bondClaims.push(tier);S.coins+=tier*60;give('compost',tier*2);change();return true;}
function chapterCount(k){if(Object.hasOwn(S.stats,k))return S.stats[k];if(k==='restoration')return S.village.restoration;if(k==='deliveries'||k==='fishCaught')return S.village[k];if(k==='pier')return +S.village.pier;if(k==='explored')return S.life.explored;if(k==='cats')return S.cats.length;if(k==='decor')return S.decor.length;if(k==='bonds')return S.cats.filter(c=>bondRank(c)>=1).length;if(k==='discoveries')return S.village.discovered.length;if(k==='store')return S.storeLevel;if(k==='buildings')return S.buildings.filter(b=>b.ready<=now()).length;if(k==='parcels')return S.parcels.length;return +S.buildings.some(b=>b.type===k&&b.ready<=now());}
function claimChapter(n){n=+n;const claimed=S.life.chapters||[],ch=CHAPTERS[n];if(!ch||n!==claimed.length||ch.goals.some(([k,target])=>chapterCount(k)<target))return false;S.life.chapters ||= [];S.life.chapters.push(n);S.coins+=ch.coins;for(const[k,count]of Object.entries(ch.goods))give(k,count);change();return true;}
function buyRoomItem(k){const d=ROOM_ITEMS[k];if(!d)return false;const room=S.life.room||{owned:[],slots:{}};if(room.owned.includes(k)||S.coins<d.coins||!has(d.need))return false;S.coins-=d.coins;take(d.need);room.owned.push(k);const slot=['left','centre','right'].find(s=>!room.slots[s]);if(slot)room.slots[slot]=k;S.life.room=room;change();return true;}
function placeRoomItem(args){const[k,slot]=args.split(','),r=S.life.room;if(!r||!r.owned.includes(k)||!['left','centre','right','store'].includes(slot))return false;for(const s of Object.keys(r.slots))if(r.slots[s]===k)delete r.slots[s];if(slot!=='store')r.slots[slot]=k;change();return true;}
function roomPanel(){const r=S.life.room||{owned:[],slots:{}};return '<div class="room-stage"><img class="room-base" src="art/life-5.webp" alt="Inside your cat cottage">'+Object.entries(r.slots).map(([slot,k])=>'<img class="room-piece '+slot+'" src="art/'+ROOM_ITEMS[k].art+'.webp" alt="'+ROOM_ITEMS[k].name+'">').join('')+S.cats.filter(c=>c.job?.kind==='home').map((c,i)=>'<img class="room-cat '+(c.job.label.includes('Resting')?'resting':c.job.label.includes('Eating')?'eating':'playing')+' room-cat-'+i%3+'" src="art/biped-'+c.id%4+'.webp" alt="'+safe(c.name)+'">').join('')+'</div>'+homeCatsPanel()+'<p class="intro">Arrange your own cottage. Bought furnishings stay yours; changing positions is free.</p>'+Object.entries(ROOM_ITEMS).map(([k,d])=>'<div class="card"><div class="row"><img class="portrait" src="art/'+d.art+'.webp" alt=""><h2>'+d.name+'</h2></div>'+(r.owned.includes(k)?'<div class="tabs">'+['left','centre','right','store'].map(s=>btn(r.slots[s]===k?'✓ '+s:s,'roomPlace',k+','+s,false,true)).join('')+'</div>':'<p>'+needs(d.need)+'</p>'+btn('Buy · 🪙 '+d.coins,'roomBuy',k,S.coins<d.coins||!has(d.need)))+'</div>').join('');}
function communityPanel(kind){if(kind==='chapters'){const n=(S.life.chapters||[]).length;return '<p class="intro">'+n+'/8 chapters complete. Earlier progress counts toward these goals. Rewards can be claimed once; they do not add level XP.</p>'+CHAPTERS.map((ch,i)=>'<div class="card"><h2>'+(i<n?'✓ ':i>n?'🔒 ':'')+(i+1)+'. '+ch.name+'</h2><p>'+ch.text+'</p>'+ch.goals.map(([k,target,label])=>'<p>'+label+' · '+Math.min(target,chapterCount(k))+'/'+target+'</p>').join('')+'<p>Reward: '+ch.coins+' coins · '+Object.entries(ch.goods).map(([k,v])=>ITEMS[k].name+' ×'+v).join(', ')+'</p>'+btn(i<n?'Claimed':i>n?'Complete previous chapter':'Claim chapter reward','chapter',i,i!==n||ch.goals.some(([k,t])=>chapterCount(k)<t))+'</div>').join('');}
if(kind==='friends')return '<p class="intro">Help each cat once a day. Affection and friendship both need 25, 60 and 100 points for the three bond ranks. Each rank makes that cat’s farming, cooking and deliveries 2% faster.</p>'+S.cats.map(c=>{const r=catRequest(c),rank=bondRank(c);return '<div class="card"><div class="row"><img class="portrait" src="art/biped-'+c.id%4+'.webp" alt=""><h2>'+safe(c.name)+' · '+['New friend','Good friend','Close friend','Best friend'][rank]+'</h2></div><p>Affection '+(c.affection||0)+'/100 · Friendship '+(c.friendship||0)+'/100</p><p>'+safe(c.name)+' would like '+r.count+' '+ITEMS[r.item].name+'.</p><p>'+needs({[r.item]:r.count})+'</p>'+btn(r.done?'Helped today':'Give · earn '+r.coins+' coins','catRequest',c.id,r.done||!has({[r.item]:r.count}))+'<p>Helping gives +10 affection and +8 friendship.</p>'+[1,2,3].map(t=>btn((c.bondClaims||[]).includes(t)?'Rank '+t+' claimed':'Rank '+t+' gift','bond',c.id+','+t,rank<t||(c.bondClaims||[]).includes(t),true)).join(' ')+'</div>';}).join('');
if(kind==='cookbook')return '<p class="intro">Find the workshop and ingredients for every recipe.</p><div class="tabs">'+[...new Set(Object.values(RECIPES).map(r=>r.at))].map(k=>btn((recipeTab===k?'✓ ':'')+BUILDINGS[k].name,'recipeTab',k,false,true)).join('')+'</div>'+Object.entries(RECIPES).filter(([k,r])=>r.at===recipeTab).map(([k,r])=>{const b=S.buildings.find(b=>b.type===r.at);return '<div class="card"><h2>'+ITEMS[k].icon+' '+ITEMS[k].name+'</h2><p>'+BUILDINGS[r.at].name+' · Level '+Math.max(r.level,BUILDINGS[r.at].level)+' · '+remaining(now()+r.time*1000)+'</p><p>'+needs(r.need)+'</p>'+(b?btn('Open kitchen','building',b.id):btn('Build kitchen','place',r.at,level()<BUILDINGS[r.at].level||S.coins<BUILDINGS[r.at].cost))+'</div>';}).join('');return '';}
