'use strict';
const FarmLife=(()=>{
 function state(){S.farmLife ||= {projects:{},shipment:null,shipSerial:0,stall:null,quality:0};return S.farmLife;}
 function log(s){if(typeof FarmNavigation!=='undefined')FarmNavigation.log(s);}
 function project(key){const d=TOWN_PROJECTS[key],s=state(),stage=s.projects[key]||0;if(!d||!S.buildings.some(b=>b.type==='town_'+key&&b.ready<=now())||level()<d.level||stage>=3||!has(d.need[stage]))return false;take(d.need[stage]);s.projects[key]=stage+1;if(stage===2){if(key==='park')for(const c of S.cats)c.friendship=Math.min(100,(c.friendship||0)+5);if(key==='school')for(const c of S.cats){c.skills ||= {farm:0,cook:0,haul:0};c.skills.farm+=10;c.skills.cook+=10;}if(key==='townhall')S.coins+=2000;}log(d.name+' · stage '+(stage+1)+'/3');change();return true;}
 function projects(){return '<p>Permanent village projects. Each stage is paid once; there are no expiry penalties.</p>'+Object.entries(TOWN_PROJECTS).map(([k,d])=>{const stage=state().projects[k]||0;return '<div class="card"><h2>'+d.name+' · '+stage+'/3</h2><div class="project-scene project-'+k+' stage-'+stage+'"><img src="art/town-'+k+'.webp" alt="'+d.name+'"></div><p>'+d.bonus+'</p>'+(!S.buildings.some(b=>b.type==='town_'+k)?btn('Choose project location','place','town_'+k,level()<d.level,true):'<p>Located on your farm</p>')+(stage<3?'<p>'+needs(d.need[stage])+'</p>'+btn(level()<d.level?'Unlocks at level '+d.level:'Build stage '+(stage+1),'townProject',k,level()<d.level||!S.buildings.some(b=>b.type==='town_'+k&&b.ready<=now())||!has(d.need[stage])):'<p>✓ Completed permanently</p>')+'</div>';}).join('');}
 function shipOffer(){const n=state().shipSerial,pools=[{wheat:8,bread:3,egg:4},{corn:8,milk:4,butter:2},{carrot:8,juice:3,flower:4}];return pools[n%pools.length];}
 function loadShip(item){const s=state();if(level()<15||!S.village.pier)return false;s.shipment ||= {need:{...shipOffer()},loaded:{},end:0};const q=s.shipment,n=q.need[item];if(q.end||!n||q.loaded[item]||!has({[item]:n}))return false;take({[item]:n});q.loaded[item]=n;change();return true;}
 function sail(){const q=state().shipment;if(!q||q.end||Object.entries(q.need).some(([k,n])=>q.loaded[k]!==n))return false;q.end=now()+180000;log('Cargo ship departed');change();return true;}
 function claimShip(){const s=state(),q=s.shipment;if(!q?.end||q.end>now())return false;const coins=Object.entries(q.need).reduce((n,[k,v])=>n+(ITEMS[k].value||20)*v,0);S.coins+=Math.round(coins*1.5);give('compost',3);give('seed_tray',1);s.shipment=null;s.shipSerial++;log('Cargo ship returned · shipment rewarded');change();return true;}
 function cancelShip(){const s=state(),q=s.shipment;if(!q||q.end)return false;for(const[k,n]of Object.entries(q.loaded))give(k,n);s.shipment=null;change();return true;}
 function ship(){const s=state(),q=s.shipment,need=q?.need||shipOffer();return '<div class="card"><h2>Harbour shipment</h2><p>Unlocks at level 15 with a fishing pier. Load three crates, sail, then collect the return reward. Loaded stock is reserved. No deadline.</p><div class="ship-scene '+(q?.end>now()?'sailing':'')+'">⛵</div>'+Object.entries(need).map(([k,n])=>'<div class="row"><span>'+ITEMS[k].icon+' '+ITEMS[k].name+' × '+n+'</span>'+btn(q?.loaded[k]?'Loaded':'Load crate','shipLoad',k,level()<15||!S.village.pier||!!q?.loaded[k]||!!q?.end||!has({[k]:n}))+'</div>').join('')+(q?.end?'<p>Return: '+remaining(q.end)+'</p>'+btn('Collect ship reward','shipClaim','',q.end>now()):btn('Send ship · 3 minutes','shipSail','',!q||Object.keys(q.loaded).length!==3)+btn('Unload reserved crates','shipCancel','',!q,true))+'<p>Reward: 150% of base goods value, 3 compost and 1 seed tray. Completed: '+s.shipSerial+'</p></div>';}
 function stallList(item){const s=state();if(s.stall||!ITEMS[item]||!has({[item]:5})||!CROPS[item]&&!TREES[item])return false;take({[item]:5});s.stall={item,count:5,end:now()+120000};change();return true;}
 function stallClaim(){const s=state(),q=s.stall;if(!q||q.end>now())return false;const value=Math.round(ITEMS[q.item].value*q.count*1.2);S.coins+=value;s.stall=null;log('Roadside stall sold goods · '+value+' coins');change();return true;}
 function stall(){const q=state().stall;return '<p>Put five extra fruit or crops on your roadside stall. A village customer buys them after two minutes for 20% above base value.</p>'+(q?'<div class="card"><h2>'+ITEMS[q.item].name+' × 5</h2><p>'+remaining(q.end)+'</p>'+btn('Collect payment','stallClaim','',q.end>now())+'</div>':Object.keys({...CROPS,...TREES}).filter(k=>ITEMS[k]&&has({[k]:5})).map(k=>btn(ITEMS[k].icon+' '+ITEMS[k].name+' × 5','stallList',k,false,true)).join('')||'<p>Keep at least five of a crop or fruit in your barn.</p>');}
 function tailorHat(key){if(!HatShop.catalog[key]||S.hatCollection?.includes(key)||!S.buildings.some(b=>b.type==='tailor'&&b.ready<=now())||!has({wovencloth:2}))return false;take({wovencloth:2});(S.hatCollection ||= []).push(key);log('Tailored '+HatShop.catalog[key].name);change();return true;}
 function greenStart(args){const[id,item]=args.split(','),b=readyBuilding(+id);if(b?.type!=='greenhouse'||b.greenBatch||b.lifeEnd||!['herb','flower','cocoa'].includes(item)||item==='cocoa'&&level()<26||!has({fiber:2,compost:1}))return false;const c=assign('Tending greenhouse',b,now()+5000,'produce');if(!c)return false;take({fiber:2,compost:1});b.greenBatch={item,end:Math.max(now(),c.job.workStart||0)+120000};change();return true;}
 function greenCollect(id){const b=readyBuilding(+id),q=b?.greenBatch;if(!q||q.end>now())return false;queueCargo(q.item,3,b);delete b.greenBatch;change();return true;}
 function greenPanel(b){const q=b.greenBatch;return '<div class="card"><h2>Greenhouse seed beds</h2><p>Choose herbs, flowers or cocoa. Each batch uses 2 fiber and 1 compost; produces 3 goods in two minutes.</p>'+(q?'<p>'+ITEMS[q.item].name+' · '+remaining(q.end)+'</p>'+btn('Collect seed bed','greenCollect',b.id,q.end>now()):['herb','flower','cocoa'].map(k=>btn(ITEMS[k].icon+' '+ITEMS[k].name,'greenStart',b.id+','+k,!!b.lifeEnd||!has({fiber:2,compost:1})||k==='cocoa'&&level()<26)).join(''))+'</div>';}
 const oldZone=zoneResource;zoneResource=function(k,i){return k==='cave'&&i%5===0?{key:'clay',sprite:'resource-4',count:3}:oldZone(k,i);};
 const oldField=fieldAction;fieldAction=function(id){const f=S.fields.find(f=>f.id===id),crop=f?.crop,quality=!!f?.fertilized,ready=crop&&f.end<=now(),ok=oldField(id);if(ok&&ready&&quality){state().quality++;queueCargo(crop,1,f);log('Quality harvest · bonus '+ITEMS[crop].name);}if(ok&&!crop&&f.crop&&weather()==='Rain'){f.end=now()+(f.end-now())*.92;f.rainWatered=true;const c=S.cats.find(c=>c.job?.crop===f.crop);if(c)c.job.end=Math.max(...S.fields.filter(p=>p.crop===f.crop).map(p=>p.end));saveGame();}return ok;};
 const oldAnimal=buyAnimal;buyAnimal=function(id){const b=readyBuilding(id),ok=oldAnimal(id);if(ok){b.animalBorn ||= Array(b.animals-1).fill(0);while(b.animalBorn.length<b.animals-1)b.animalBorn.push(0);b.animalBorn.push(now());saveGame();}return ok;};actions.animal=id=>buyAnimal(+id);
 const oldLife=startLifeProduction;startLifeProduction=function(id){const b=S.buildings.find(b=>b.id===+id);if(b?.greenBatch)return false;return oldLife(id);};actions.lifeStart=startLifeProduction;
 const oldUpgrade=upgradeWorkshop;upgradeWorkshop=function(id){const b=S.buildings.find(b=>b.id===+id);return b?.greenBatch||BUILDINGS[b?.type]?.project?false:oldUpgrade(id);};actions.workshopUpgrade=upgradeWorkshop;
 const oldBusy=objectBusy;objectBusy=function(o){return !!o.greenBatch||oldBusy(o);};
 const oldReady=readyGoods;readyGoods=function(){return oldReady()+S.buildings.filter(b=>b.greenBatch?.end<=now()).length;};
 const oldCollect=collectAll;collectAll=function(){let extra=false;for(const b of S.buildings)if(b.greenBatch?.end<=now())extra=greenCollect(b.id)||extra;return oldCollect()||extra;};actions.collectAll=collectAll;
 const oldRender=renderPanel;renderPanel=function(){const pb=panel==='building'&&S.buildings.find(b=>b.id===panelId);if(pb&&BUILDINGS[pb.type]?.project)panel='town';const custom={town:projects,ship,stall};if(custom[panel]){$('sheetTitle').textContent=({town:'Village projects',ship:'Cargo ship',stall:'Roadside stall'})[panel];$('sheetBody').innerHTML=custom[panel]();return;}oldRender();const b=S.buildings.find(b=>b.id===panelId);if(panel==='lifeBuilding'&&b?.type==='greenhouse')$('sheetBody').insertAdjacentHTML('beforeend',greenPanel(b));if(panel==='building'&&b&&!BUILDINGS[b.type].animal&&!BUILDINGS[b.type].life){const n=b.upgrade||0;$('sheetBody').insertAdjacentHTML('beforeend','<div class="card"><h2>Upgrade preview</h2><p>'+ (n>=2?'Fully upgraded.':(3+n)+' → '+(4+n)+' queue slots · production speed bonus '+(n*15)+'% → '+((n+1)*15)+'%')+'</p><p>Appearance: additional workshop fittings and level badge.</p></div>');}if(panel==='building'&&b?.type==='tailor')$('sheetBody').insertAdjacentHTML('beforeend','<div class="card"><h2>Make a wearable hat</h2><p>2 woven cloth. Ownership is shared with Hat shop; making a hat does not equip it.</p>'+Object.entries(HatShop.catalog).map(([k,d])=>btn(S.hatCollection?.includes(k)?d.name+' · Owned':'Make '+d.name,'tailorHat',k,S.hatCollection?.includes(k)||!has({wovencloth:2})||b.ready>now())).join('')+'</div>');};
 Object.assign(actions,{townProject:project,shipLoad:loadShip,shipSail:sail,shipClaim:claimShip,shipCancel:cancelShip,stallList,stallClaim,tailorHat,greenStart,greenCollect});
 const oldValidate=validate;validate=function(a){const f=a?.farmLife;if(f){if(!f.projects||Object.entries(f.projects).some(([k,v])=>!TOWN_PROJECTS[k]||!Number.isInteger(v)||v<0||v>3)||!Number.isInteger(f.shipSerial)||f.shipSerial<0||!Number.isInteger(f.quality)||f.quality<0)return false;const q=f.shipment;if(q&&(!q.need||!q.loaded||!Number.isFinite(q.end)||q.end<0||Object.entries(q.need).some(([k,n])=>!ITEMS[k]||!Number.isInteger(n)||n<1||n>100)||Object.entries(q.loaded).some(([k,n])=>q.need[k]!==n)))return false;if(f.stall&&(!ITEMS[f.stall.item]||f.stall.count!==5||!Number.isFinite(f.stall.end)))return false;}if(a?.buildings?.some(b=>b.greenBatch&&(!['herb','flower','cocoa'].includes(b.greenBatch.item)||!Number.isFinite(b.greenBatch.end))))return false;return oldValidate(a);};
 return {state,project,loadShip,sail,claimShip,cancelShip,shipOffer,greenStart,greenCollect};
})();
