'use strict';
function goalsPanel(compact=false){
 const goals=nextGoals();return '<p class="intro">A few meaningful next steps. Pin a goal to keep it first; your earlier progress counts.</p>'+goals.map(g=>'<div class="card goal-card"><h2>'+safe(g.text)+'</h2><p>'+Math.floor(g.n)+' / '+g.total+'</p><div class="progress"><i style="width:'+Math.min(100,g.n/g.total*100)+'%"></i></div>'+btn('Continue','goalGo',g.id)+btn(S.journey.goal===g.id?'★ Pinned':'Pin goal','goalPin',g.id,false,true)+'</div>').join('')+(compact?'':'<div class="menu-grid"><button data-open="chapters">Village chapters</button><button data-open="unlocks">Upcoming unlocks</button><button data-open="customers">Neighbour stories</button><button data-open="valley">Valley projects</button></div>');
}
function catMemoriesPanel(){
 return '<p class="intro">Every cat has a favourite food, a favourite kind of work, and three memories to share. Gifts help both friendship and affection; unlocked clothes stay in that cat’s wardrobe.</p>'+S.cats.map(c=>{
  const p=catProfile(c),j=S.journey.cats[c.id],rank=bondRank(c);
  return '<div class="card memory-card"><div class="row"><img class="portrait" src="art/biped-'+c.id%4+'.webp" alt=""><div><h2>'+safe(c.name)+' · '+p.personality+'</h2><p>'+safe(personalityBenefit(c))+' · enjoys '+{farm:'farming',cook:'cooking',haul:'helping with deliveries'}[p.work]+'</p></div></div><p>♥ '+(c.affection||0)+'/100 affection · '+(c.friendship||0)+'/100 friendship</p><p>Favourite: '+ITEMS[p.food].icon+' '+ITEMS[p.food].name+' · '+quantity(p.food)+' in barn</p>'+btn(j.giftDay===day()?'Favourite treat shared today':'Share favourite · +8 friendship & affection','favoriteGift',c.id,j.giftDay===day()||!has({[p.food]:1}))+p.memories.map((text,i)=>'<div class="memory-entry '+(j.memories.includes(i+1)?'unlocked':'')+'"><h3>'+['A first connection','Growing together','A place to belong'][i]+'</h3><p>'+(j.memories.includes(i+1)?'“'+text+'”':'Unlocks at friendship rank '+(i+1)+' ('+[25,60,100][i]+' affection and friendship).')+'</p>'+btn(j.memories.includes(i+1)?'Memory saved':'Read memory · outfit + '+(i+1)*80+' coins','memory',c.id+','+(i+1),j.memories.includes(i+1)||rank<i+1,true)+'</div>').join('')+'</div>';
 }).join('')+'<div class="menu-grid"><button data-open="friends">Daily cat requests</button><button data-open="interior">Cottage activities</button><button data-open="wardrobe">Wear friendship rewards</button></div>';
}
function customersPanel(){
 return '<p class="intro">Each completed store order counts as a visit for that neighbour. Build a relationship, help with three little projects, and receive a keepsake for your farm. Familiar customers also pay up to 8% extra.</p>'+Object.entries(CUSTOMER_STORIES).map(([name,d])=>{
  const c=S.journey.customers[name],i=c.chapter,complete=i===3;
  return '<div class="card story-card"><h2>🐱 '+name+' · '+d.role+'</h2><p>'+c.visits+' visits · '+c.chapter+'/3 story chapters · '+customerBonus({name})+'% friendship tip</p>'+d.titles.map((title,n)=>'<span class="story-step '+(n<i?'done':'')+'">'+(n<i?'✓ ':'')+title+'</span>').join('')+(complete?'<p>'+d.lines[2]+'</p><p>♥ '+DECOR_SHOP[d.decor].name+' earned.</p>':'<blockquote>'+d.lines[i]+'</blockquote><p>'+c.visits+'/'+[3,8,15][i]+' visits · level '+d.levels[i]+'</p><p>'+needs(d.needs[i])+'</p><p>Reward: '+[120,280,650][i]+' coins + '+(i===2?DECOR_SHOP[d.decor].name:'3 compost')+'</p>'+btn('Help '+name,'customerStory',name,c.visits<[3,8,15][i]||level()<d.levels[i]||!has(d.needs[i])))+'</div>';
 }).join('')+'<button class="action" data-open="orders">Serve returning neighbours</button>';
}
function seasonalMarketPanel(){
 const season=seasonInfo(),m=S.journey.market;
 return '<div class="card season-banner" style="--season-color:'+season.color+'"><h2>'+season.icon+' '+season.name+'</h2><p>'+season.text+'</p><p>Next season in <span data-time="'+season.ends+'">'+remaining(season.ends)+'</span>. A season lasts 7 days; the four-season cycle repeats.</p><b>🎟 '+m.tokens+' market tickets</b><p>Tickets and learned recipes never expire. Every decoration returns to this market.</p></div><h2>Today’s market challenges</h2>'+MARKET_TASKS.map(t=>{
  const n=Math.min(t.target,marketProgress(t)),done=m.claimed.includes(t.id);
  return '<div class="card"><h3>'+t.name+'</h3><p>'+n+'/'+t.target+' · '+t.tokens+' tickets</p><div class="progress"><i style="width:'+n/t.target*100+'%"></i></div>'+btn(done?'Claimed today':'Claim tickets','marketTask',t.id,done||n<t.target)+'</div>';
 }).join('')+'<h2>Festival recipe collection</h2><p class="intro">Learn once for 5 tickets, then cook in any season. Normal level and workshop requirements apply.</p><div class="grid">'+SEASONS.map(s=>{
  const r=RECIPES[s.recipe],learned=S.journey.learned.includes(s.recipe);
  return '<div class="card"><h3>'+ITEMS[s.recipe].icon+' '+ITEMS[s.recipe].name+'</h3><p>'+BUILDINGS[r.at].name+' · level '+r.level+'</p><p>'+needs(r.need)+'</p>'+btn(learned?'Learned permanently':'Learn · 5 tickets','marketRecipe',s.recipe,learned||level()<r.level||m.tokens<5)+(learned?btn('Open workshop','planSource',s.recipe,false,true):'')+'</div>';
 }).join('')+'</div><h2>Market rewards</h2><div class="grid">'+Object.entries(MARKET_PRIZES).map(([key,p])=>'<div class="card"><h3>'+ITEMS[key].icon+' '+ITEMS[key].name+' ×'+p.count+'</h3><p>'+quantity(key)+' in barn</p>'+btn('Trade · '+p.cost+' tickets','marketPrize',key,m.tokens<p.cost)+(DECOR_SHOP[key]?btn('Place reward','place',key,!quantity(key),true):'')+'</div>').join('')+'</div>';
}
function valleyProjectsPanel(){
  return '<h2>Level 50+ Farm research</h2><p class="intro">Late-game crops and trees unlock at their normal levels and can grow on Main Farm. These optional research milestones also work without unlocking Second Land. Gather sunstone and hardwood from Main Farm resources after level 50.</p>'+Object.entries(VALLEY_PROJECTS).map(([key,p])=>{
  const done=S.journey.projects.includes(key),status=projectStatus(key);
   return '<div class="card project-card"><h2>'+(done?'✓ ':'')+p.name+' · level '+p.level+'</h2><p>'+p.text+'</p><p>Clear '+p.clear+' resources · '+projectClearingProgress()+' cleared</p><p>'+needs(p.need)+' · '+p.coins.toLocaleString()+' coins</p><p>'+status.reason+'</p>'+btn(done?'Restored':'Complete research','valleyProject',key,!status.ok)+'</div>';
  }).join('')+'<h2>Main Farm crops & recipes</h2><div class="grid">'+[...Object.entries(CROPS).filter(([,d])=>d.valley),['starfruit',TREES.starfruit]].map(([key,d])=>'<div class="card"><h3>'+d.icon+' '+d.name+'</h3><p>Level '+d.level+' · Main Farm compatible</p><p>'+cropAccess(key).reason+'</p>'+btn(CROPS[key]?'Choose crop on Main Farm':'Place tree on Main Farm','valleyCrop',key,!cropAccess(key).ok)+'</div>').join('')+'</div><button class="action secondary" data-open="cookbook">Explore late-game recipes</button>';
}
function layoutMap(entries){
 const minX=Math.min(0,...entries.map(e=>e.x)),minY=Math.min(0,...entries.map(e=>e.y)),maxX=Math.max(S.eastValley?SUNRISE_MAP.x+SUNRISE_MAP.size:S.size,...entries.map(e=>e.x+2)),maxY=Math.max(24,...entries.map(e=>e.y+2));
  const channel=S.eastValley?'<rect x="'+mainShore(S)+'" y="'+minY+'" width="'+(SUNRISE_MAP.x-mainShore(S))+'" height="'+(maxY-minY)+'" fill="#8bc8cd"/>':'';
 return '<svg class="layout-map" viewBox="'+minX+' '+minY+' '+(maxX-minX)+' '+(maxY-minY)+'" role="img" aria-label="Farm layout preview"><rect x="'+minX+'" y="'+minY+'" width="'+(maxX-minX)+'" height="'+(maxY-minY)+'" fill="#dceac0"/><rect x="'+minX+'" y="10" width="'+(maxX-minX)+'" height="2" fill="#8bc8cd"/>'+channel+entries.map(e=>{
  const size=BUILDINGS[e.type]?.size||DECOR_SHOP[e.type]?.size||1,color={buildings:'#d49d66',fields:'#a98a54',trees:'#739751',decor:'#c48caa'}[e.kind];
  return '<rect x="'+e.x+'" y="'+e.y+'" width="'+size+'" height="'+size+'" rx=".15" fill="'+color+'" stroke="#fff6dc" stroke-width=".12"><title>'+safe((BUILDINGS[e.type]||DECOR_SHOP[e.type]||TREES[e.type])?.name||'Field')+'</title></rect>';
 }).join('')+'</svg>';
}
function layoutsPanel(){
 return '<p class="intro">Save up to three arrangements: production, pretty gardens or festival day. Preview both layouts before applying. New objects stay where they are. Busy jobs and active deliveries must finish before their objects move.</p><div class="card"><h2>Save this arrangement</h2><label class="input-label">Preset name<input id="layoutName" maxlength="32" placeholder="Production / Garden / Festival" value="My farm '+(S.journey.layouts.length+1)+'"></label>'+btn('Save current layout','layoutSave','',S.journey.layouts.length>=3)+btn('Undo last move / layout','layoutUndo','',!layoutUndo,true)+'</div>'+S.journey.layouts.map(l=>{
  const check=layoutCheck(l.entries);return '<div class="card"><h2>'+safe(l.name)+'</h2>'+layoutMap(l.entries)+'<p>'+l.entries.length+' saved objects · '+check.reason+'</p>'+btn('Preview & apply','layoutPreview',l.id,false,true)+btn('Delete preset','layoutDelete',l.id,false,true)+'</div>';
 }).join('')+'<div class="layout-legend">🟫 Buildings · fields & paths · 🟩 Trees · 🟪 Decorations</div>';
}
function layoutPreviewPanel(id){
 const l=S.journey.layouts.find(l=>l.id===+id);if(!l)return '<p>That layout is no longer saved.</p>';const check=layoutCheck(l.entries);
 return '<h2>'+safe(l.name)+'</h2><div class="layout-comparison"><div><h3>Current farm</h3>'+layoutMap(layoutEntries())+'</div><div><h3>Saved arrangement</h3>'+layoutMap(l.entries)+'</div></div><p>'+check.reason+'</p><p>Applying changes positions only. Crops, inventory, cats and production progress stay attached to their objects.</p>'+btn('Apply this layout','layoutApply',id,!check.ok||!check.changed?.length)+btn('Back to presets','layoutBack','',false,true);
}
function plannerExtras(p){
 const problems=plannerBottlenecks(p),reserved=S.journey.reserved.filter(id=>S.orders.some(o=>o.id===id));
 return '<div class="card"><h2>Order stock protection</h2><p>'+reserved.length+' orders protected. Requested goods cannot be sold, cooked or spent on other customers. Other ingredients and future production stay shared.</p>'+btn('Protect selected orders','planReserve','',!p.orders.length)+btn('Release protected stock','planRelease','',!reserved.length,true)+'</div>'+(problems.length?'<div class="card bottleneck"><h2>What is holding the plan up?</h2>'+problems.map(r=>'<p>'+safe(r.text)+' '+(r.panel?'<button data-open="'+r.panel+'">Open</button>':btn('Go','planSource',r.key,false,true))+'</p>').join('')+'</div>':'')+'<div class="card"><h2>Pinned ingredients</h2><p>Keep frequently needed goods at hand. Pins stay saved between sessions.</p>'+(S.journey.pins.length?S.journey.pins.map(k=>'<div class="pin-row"><b>'+ITEMS[k].icon+' '+ITEMS[k].name+' · '+quantity(k)+'</b>'+btn('Open source','planSource',k,false,true)+btn('Unpin','planPin',k,false,true)+'</div>').join(''):'<p>Use Pin beside a production step to add an ingredient.</p>')+'</div>';
}
function audioSettingsPanel(){return '<div class="card"><h2>Farm sound mix</h2><p>Gentle music, river ambience and different action sounds. Enable Sound above to listen.</p>'+[['music','Music'],['ambience','River ambience'],['effects','Action sounds']].map(([key,label])=>'<label class="audio-slider">'+label+'<input type="range" min="0" max="100" step="5" data-audio="'+key+'" value="'+Math.round(S.journey.audio[key]*100)+'" aria-label="'+label+' volume"></label>').join('')+'</div><div class="card"><h2>A keepsake from your farm</h2><p>Save a picture of the current island view, without the menus.</p>'+btn('Download farm picture','farmPicture','',false,true)+'</div>';}
function journeyPanel(kind,id){return ({goals:goalsPanel,memories:catMemoriesPanel,customers:customersPanel,seasons:seasonalMarketPanel,layouts:layoutsPanel,layoutPreview:()=>layoutPreviewPanel(id)})[kind]?.()||'';}
