'use strict';
const DOCK_SITE={x:2,y:9,size:1},BOAT_SITE={x:12,y:10.6,size:1};
function shopCategory(k){return DECOR_SHOP[k].category||(k==='guesthouse'?'homes':'fences');}
function storeDecoration(id){const i=S.decor.findIndex(d=>d.id===+id);if(i<0)return false;const d=S.decor[i];if(d.end&&d.end>now()){gameNotice('Wait for the flowers to finish growing.');return false;}if(d.type==='guesthouse'&&S.cats.length>Math.min(12,4+(S.houseLevel||0)*3+(S.decor.filter(x=>x.type==='guesthouse').length-1)*2)){gameNotice('Your cats still need this guest cottage.');return false;}if(['planter','flowercorner'].includes(d.type)&&d.end){gameNotice('Collect the flowers before storing this planter.');return false;}S.decor.splice(i,1);give(d.type,1);change();return true;}
function useGarden(id){
 const d=S.decor.find(d=>d.id===+id);if(!d)return false;
 if(['handcart','deliverycrate','producecrate'].includes(d.type)){const q=S.village?.cargo.find(q=>!q.end);if(!q)return false;if(typeof prioritizeCargo==='function')prioritizeCargo(q.id);gameNotice('Cart loaded: delivery prioritized.');return true;}
 if(d.type==='merchantcart'){if(!S.village||S.village.merchant.arrives>now())return false;return tradeBoat();}
 if(d.type==='smallrowboat'){openPanel('fishing');return true;}
 if(d.type==='lamp'){d.off=!d.off;change();return true;}
 if(['planter','flowercorner'].includes(d.type)){
  if(d.end){if(d.end>now())return false;queueCargo('flower',d.type==='flowercorner'?4:2,d);d.end=0;change();return true;}
  const cat=assign('Watering flowers',{...d,size:1},now()+5000,'water');if(!cat)return false;d.end=Math.max(now(),cat.job.workStart||0)+90000;change();return true;
 }
 if(!['picnic','fountain'].includes(d.type)||(d.used===day()||S.life.gardenDays?.[d.type]===day()))return false;
 if(d.type==='picnic'){if(!has({bread:1,milk:1}))return false;take({bread:1,milk:1});for(const c of S.cats)c.friendship=Math.min(100,(c.friendship||0)+5);}else for(const c of S.cats)c.affection=Math.min(100,(c.affection||0)+3);
 d.used=day();S.life.gardenDays ||= {};S.life.gardenDays[d.type]=day();for(const c of S.cats)if(!c.job||c.job.end<=now())c.job={kind:'social',label:d.type==='picnic'?'Sharing a picnic':'Meeting at the fountain',target:d.id,x:d.x+(DECOR_SHOP[d.type].size||1)+.3,y:d.y+.5+c.id%3*.35,end:now()+10000};change();return true;
}
function giftFlower(id){const c=S.cats.find(c=>c.id===+id);if(!c||!availableQuantity('flower')||c.flowerDay===day())return false;take({flower:1});c.flowerDay=day();c.affection=Math.min(100,(c.affection||0)+8);change();return true;}
function gardenPanel(d){const info=DECOR_SHOP[d.type];let html='<p>'+ (info?.description||'Place, rotate or store this decoration.')+'</p>';if(['handcart','deliverycrate','producecrate'].includes(d.type))html+='<p>Prioritizes the next waiting delivery for a cat.</p>'+btn('Load next delivery','gardenUse',d.id,!S.village?.cargo.some(q=>!q.end));if(d.type==='merchantcart')html+='<p>Use the market cart for the next merchant trade.</p>'+btn('Trade with merchant','gardenUse',d.id,!S.village||S.village.merchant.arrives>now());if(d.type==='smallrowboat')html+='<p>Return to the river fishing controls.</p>'+btn('Open fishing','gardenUse',d.id);if(['planter','flowercorner'].includes(d.type))html+='<p>Grow flowers for bouquets and garlands · 90 seconds.</p>'+btn(d.end?d.end>now()?'Growing · '+remaining(d.end):'Collect flowers':'Water planter','gardenUse',d.id,d.end>now());if(d.type==='lamp')html+=btn(d.off?'Turn on':'Turn off','gardenUse',d.id);if(['picnic','fountain'].includes(d.type))html+='<p>'+(d.type==='picnic'?needs({bread:1,milk:1}):'Meet by the fountain, once a day.')+'</p>'+btn((d.used===day()||S.life.gardenDays?.[d.type]===day())?'Enjoyed today':d.type==='picnic'?'Share picnic':'Gather cats','gardenUse',d.id,d.used===day()||S.life.gardenDays?.[d.type]===day()||d.type==='picnic'&&!has({bread:1,milk:1}));if(d.type==='signpost')html+='<button data-open="overview">Open farm overview</button>';return html;}
function mountainPanel(){return '<div class="card"><img class="room-view" src="art/mountain.webp" alt="Mountain ridge and mine entrance"><h2>Willow mountain</h2><p>Explore Crystal cave to mine stone, iron and crystals. Bring your finds home for building upgrades and crafting.</p>'+btn(level()<5?'Unlocks at level 5':'Enter Crystal cave','visit','cave',level()<5||!freeCat())+'<button data-open="tools">Upgrade pickaxe</button></div>';}

const VALLEY_PRICE=25000;
 function unlockValley(){if(S.eastValley||level()<50||S.coins<VALLEY_PRICE)return false;S.coins-=VALLEY_PRICE;S.eastValley=true;S.valleyMapRevision=SUNRISE_MAP.revision;S.valleyGeometryRevision=SUNRISE_MAP.geometryRevision;
  // The resources frame the new land and leave several clear meadow terraces
  // for fields, homes and future village buildings. They are ordinary saved
  // resource nodes, not thousands of decorative interactive objects.
  for(let x=SUNRISE_MAP.x+2;x<SUNRISE_MAP.x+SUNRISE_MAP.size-1;x+=3)for(let y=1;y<SUNRISE_MAP.y+SUNRISE_MAP.size-1;y+=3){const edge=x<SUNRISE_MAP.x+8||x>=SUNRISE_MAP.x+SUNRISE_MAP.size-8||y<5||y>=SUNRISE_MAP.y+SUNRISE_MAP.size-7;if(!edge||sunriseRiverTile(x,y)||sunriseApproachTile(x,y)||!inValley(x,y))continue;const n=Math.floor((x-SUNRISE_MAP.x)/3)*7+Math.floor(y/3),type=sunriseMountainTile(x,y)?['rock','ironrock'][n%2]:['grass','oak','pine','rock','ironrock','birch'][n%6];S.resources.push({id:S.nextId++,type,x,y,hits:0,end:0,respawn:0});}
  change();gameNotice('Second Land unlocked! Sunrise Crossing connects the lands. Explore the smoking volcano and mountain waterfalls.');return true;}
 function valleyPanel(){return '<div class="card"><h2>Second Land · Sunrise Valley</h2><p>A large 38 × 38 island with volcanic ridges, a broken caldera and a continuous rising smoke plume. A mountain waterfall feeds the clear winding river, which flows over two more cascades into the sea. Open green meadows accept fields and buildings; rocky slopes remain non-buildable. The grand Sunrise Crossing connects your helpers to the same barn.</p><p>Level 50+ crops, trees and production are also available on Main Farm; this island is optional.</p><p>Unlock at level 50 · 25,000 coins · current level '+level()+'</p>'+ (S.eastValley?btn('Visit Sunrise Valley','goValley')+' '+btn('View the volcano','goVolcano','',false,true)+' '+btn('Follow the mountain river','goRiver','',false,true)+' '+btn('View the connecting bridge','goBridge','',false,true)+' '+btn('View both islands','goIslands','',false,true):btn('Unlock Second Land · 25,000 coins','unlockValley','',level()<50||S.coins<VALLEY_PRICE))+'<p>Level limit: 100. Both islands share your cats, barn and coins.</p></div>';}

if(!S.routeRevision){for(const q of S.village?.cargo||[]){if(q.route){q.route=null;q.start=0;q.end=0;for(const c of S.cats)if(c.job?.cargo===q.id)c.job=null;}}S.routeRevision=1;saveGame();}
