'use strict';
let activeZone=null;
function initLife(){S.life ||= {version:1,tools:{axe:0,pickaxe:0,can:0},milestones:[],explored:0,zones:{},visit:null,festival:null,furniture:0,effects:true};for(const c of S.cats){c.role ||= 'all';c.skills ||= {farm:0,cook:0,haul:0};}if(S.life.visit){const c=S.cats.find(c=>c.id===S.life.visit.cat);if(c?.job?.kind==='visit')c.job=null;for(const[k,n]of Object.entries(S.life.visit.loot||{}))queueCargo(k,n,S.village.camp);S.life.visit=null;}if(typeof initJourney==='function')initJourney();saveGame();}
initLife();
CRAFTS.compost={name:'Compost ×2',need:{fiber:4},give:'compost',count:2};
function timeOfDay(){const t=(now()%1200000)/1200000;return t<.65?'Day':t<.8?'Evening':'Night';}
function weather(){return Math.floor(now()/300000)%4===2?'Rain':'Clear';}
function upgradeTool(k){if(!Object.hasOwn(S.life.tools,k))return false;const n=S.life.tools[k],need={wood:5+n*3,iron:2+n},kit=availableQuantity('toolparts')>0;if(n>=3||S.coins<100*(n+1)||(!has(need)&&!kit))return false;S.coins-=100*(n+1);if(has(need))take(need);else take({toolparts:1});S.life.tools[k]++;change();return true;}
function fertilizeFields(){const list=S.fields.filter(f=>f.crop&&f.end>now()&&!f.fertilized);const n=Math.min(list.length,availableQuantity('compost'));if(!n)return false;for(const f of list.slice(0,n)){const start=Math.max(now(),...S.cats.filter(c=>c.job?.fields?.includes(f.id)).map(c=>c.job.workStart||0));f.end=start+(f.end-start)*.8;f.fertilized=true;}take({compost:n});for(const c of S.cats)if(c.job?.crop)c.job.end=Math.max(now(),...S.fields.filter(f=>f.crop===c.job.crop).map(f=>f.end));change();return true;}
function careAnimals(id){const b=readyBuilding(+id);if(!b||!BUILDINGS[b.type].animal||b.cared===day())return false;const careItem=b.type==='hen'?'chicken_nest':b.type==='cow'?'cow_brush':b.type==='goat'?'goat_brush':'animal_treat',hasCare=availableQuantity(careItem)>0;if(hasCare)take({[careItem]:1});b.cared=day();b.happiness=Math.min(100,(b.happiness||0)+15+(hasCare?10:0)+(S.cats.some(c=>(c.personality||PERSONALITIES[c.id%4])==='Gentle')?5:0));change();return true;}
function animalRoutine(b,i=0){if(timeOfDay()==='Night')return 'Sleeping';const phase=(Math.floor(now()/8000)+i)%4;return phase===0?'Drinking':phase===1&&b.fed>now()?'Eating':phase===2?'Resting':'Walking';}
function startLifeProduction(id){const b=readyBuilding(+id),d=b&&LIFE_BUILDINGS[b.type];if(!d||!d.output||b.lifeEnd||!has(d.input))return false;const c=assign('Working at '+d.name,b,now()+8000,'produce');if(!c)return false;take(d.input);b.lifeEnd=Math.max(now(),c.job.workStart||0)+d.time*1000/(1+(b.upgrade||0)*.15);change();return true;}
function collectLifeProduction(id){const b=readyBuilding(+id),d=b&&LIFE_BUILDINGS[b.type];if(!d||!b.lifeEnd||b.lifeEnd>now())return false;queueCargo(d.output,d.count+(b.upgrade||0),b);b.lifeEnd=0;gainXP(5);change();return true;}
function furnishHouse(){const n=S.life.furniture;if(n>=3||S.coins<120*(n+1)||!has({plank:4}))return false;S.coins-=120*(n+1);take({plank:4});S.life.furniture++;for(const c of S.cats)c.affection=Math.min(100,(c.affection||0)+5);change();return true;}
function chooseRole(args){const[id,role]=args.split(','),c=S.cats.find(c=>c.id===+id);if(!c||!['all','farm','cook','haul'].includes(role))return false;c.role=role;change();return true;}
function claimMilestone(id){const m=VILLAGE_MILESTONES.find(m=>m.id===id);if(!m||S.life.milestones.includes(id)||!m.test())return false;S.life.milestones.push(id);S.coins+=m.reward;change();return true;}
function festivalInfo(){const kinds=[{kind:'harvest',name:'Harvest fair',target:15},{kind:'cooked',name:'Cooking contest',target:5},{kind:'fishCaught',name:'Fishing day',target:3}],serial=new Date().setHours(0,0,0,0),k=kinds[((Math.round(serial/86400000)%3)+3)%3];if(!S.life.festival||S.life.festival.day!==day())S.life.festival={day:day(),base:k.kind==='fishCaught'?S.village.fishCaught:S.stats[k.kind],claimed:false};return {...k,progress:Math.max(0,(k.kind==='fishCaught'?S.village.fishCaught:S.stats[k.kind])-S.life.festival.base),...S.life.festival};}
function claimFestival(){const f=festivalInfo();if(f.claimed||f.progress<f.target)return false;S.life.festival.claimed=true;S.coins+=180;give('bait',3);change();return true;}
function visitZone(k){const d=EXPEDITIONS[k];if(!d||level()<d.level||S.life.visit)return false;const c=freeCat();if(!c){gameNotice('A free cat is needed to explore.');return false;}if(!S.life.zones[k])S.life.zones[k]=Array.from({length:12},(_,i)=>({id:i,x:2+i%4*2,y:2+Math.floor(i/4)*2,ready:0}));S.life.visit={zone:k,cat:c.id,loot:{},x:5,y:9,work:null};c.job={kind:'visit',label:'Exploring '+d.name,target:-90,x:5,y:9,end:now()+86400000};activeZone=k;change();return true;}
function zoneResource(k,i){if(k==='woods')return {key:i%4===0?'fiber':'wood',sprite:i%4===0?'resource-8':'resource-'+i%3,count:3};if(k==='cave')return {key:i%4===0?'gem':i%2?'iron':'stone',sprite:'resource-'+(i%2?5:4),count:i%4===0?1:3};return {key:i%3===0?'pearl':'wood',sprite:i%3===0?'resource-4':'resource-3',count:i%3===0?1:3};}
function gatherZone(id){const v=S.life.visit;if(!v||v.work)return false;const node=S.life.zones[v.zone].find(n=>n.id===id);if(!node||node.ready>now())return false;const travel=Math.hypot(node.x-v.x,node.y-v.y)*550;v.work={id,start:now(),walkEnd:now()+travel,end:now()+travel+Math.max(2000,6000-(S.life.tools[v.zone==='cave'?'pickaxe':'axe']||0)*1000),fromX:v.x,fromY:v.y};change();return true;}
function exitZone(){const v=S.life.visit;if(!v)return false;const c=S.cats.find(c=>c.id===v.cat);if(c?.job?.kind==='visit')c.job=null;for(const[k,n]of Object.entries(v.loot))queueCargo(k,n,S.village.camp);S.life.visit=null;activeZone=null;change();return true;}
function lifeTick(){if(S.life.socialDay!==day()){S.life.socialDay=day();for(const c of S.cats)c.friendship=Math.min(100,(c.friendship||0)+Math.max(0,S.cats.length-1));festivalInfo();saveGame();}const v=S.life?.visit;if(v?.work&&v.work.end<=now()){if(v.work.walk){v.x=v.work.x+.5;v.y=v.work.y+1;v.work=null;change();return;}const n=S.life.zones[v.zone].find(n=>n.id===v.work.id),d=zoneResource(v.zone,n.id);const c=S.cats.find(c=>c.id===v.cat),count=d.count+(typeof catTrait==='function'&&catTrait(c)==='Curious'?1:0);v.loot[d.key]=(v.loot[d.key]||0)+count;S.life.explored+=count;n.ready=now()+300000;v.x=n.x;v.y=n.y+1;v.work=null;change();}}
function reelBonus(){const f=S.village.fishing;if(!f||f.end>now())return false;const p=((now()-f.end)%2800)/1400,position=p<=1?p:2-p;const bonus=position>=.35&&position<=.65;const item=f.item;if(!collectFish())return false;if(bonus){queueCargo(item,1,{x:6,y:8});gameNotice('Perfect catch! One extra fish.');change();}return true;}
function lifePanel(kind,id){
if(kind==='progress')return '<p class="intro">'+villageStage()+' · '+timeOfDay()+' · '+weather()+'</p>'+VILLAGE_MILESTONES.map(m=>'<div class="card"><h2>'+m.name+'</h2>'+btn(S.life.milestones.includes(m.id)?'Claimed':'Claim · 🪙 '+m.reward,'milestone',m.id,S.life.milestones.includes(m.id)||!m.test())+'</div>').join('');
if(kind==='tools')return '<p class="intro">Tools reduce gathering time. Watering upgrades and towers speed up newly planted crops.</p>'+Object.entries(S.life.tools).map(([k,n])=>'<div class="card"><h2>'+({axe:'Axe',pickaxe:'Pickaxe',can:'Watering can'}[k])+' · Level '+(n+1)+'</h2><p>'+needs({wood:5+n*3,iron:2+n})+' · or 1 Tool Parts</p>'+btn(n>=3?'Fully upgraded':'Upgrade · 🪙 '+100*(n+1),'tool',k,n>=3||S.coins<100*(n+1)||!has({wood:5+n*3,iron:2+n})&&!availableQuantity('toolparts'))+'</div>').join('')+'<div class="card"><h2>Compost</h2><p>'+availableQuantity('compost')+' available · 20% less remaining growth time · once per planting.</p>'+btn('Use on growing fields','fertilize','',!availableQuantity('compost')||!S.fields.some(f=>f.crop&&f.end>now()&&!f.fertilized))+'<button data-open="craft">Craft compost</button></div>';
if(kind==='interior')return roomPanel()+'<div class="card"><h2>Cottage comfort '+S.life.furniture+'/3</h2><p>New bedding and furniture make every cat happier.</p><p>'+needs({plank:4})+'</p>'+btn(S.life.furniture>=3?'Fully furnished':'Furnish · 🪙 '+120*(S.life.furniture+1),'furnish','',S.life.furniture>=3||S.coins<120*(S.life.furniture+1)||!has({plank:4}))+'</div>';
if(kind==='workboard')return '<p class="intro">Choose preferred work. Cats with that preference get the job first; others help if needed.</p>'+S.cats.map(c=>'<div class="card"><h2>'+safe(c.name)+'</h2><p>'+safe(c.job?.end>now()?c.job.label:'Free')+'</p><p>Farm '+(c.skills?.farm||0)+' · Cook '+(c.skills?.cook||0)+' · Delivery '+(c.experience||0)+'</p><div class="tabs">'+['all','farm','cook','haul'].map(k=>btn(k===c.role?'✓ '+k:k,'role',c.id+','+k,false,true)).join('')+'</div></div>').join('');
if(kind==='collection')return [10,20,35,50].map(n=>'<div class="card"><h2>'+n+' discoveries</h2>'+btn((S.life.discoveryClaims||[]).includes(n)?'Claimed':'Claim '+n*10+' coins + 3 bait','discovery',n,S.village.discovered.length<n||(S.life.discoveryClaims||[]).includes(n))+'</div>').join('')+'<p class="intro">'+S.village.discovered.length+' discoveries delivered to the barn.</p><div class="grid">'+Object.entries(ITEMS).filter(([k])=>!DECOR_SHOP[k]).map(([k,d])=>'<div class="card"><h2>'+d.icon+' '+(S.village.discovered.includes(k)?d.name:'Undiscovered')+'</h2></div>').join('')+'</div>';
if(kind==='festival'){const f=festivalInfo();return '<div class="card"><h2>'+f.name+'</h2><p>Today: '+Math.min(f.target,f.progress)+'/'+f.target+'</p><p>Reward: 180 coins + 3 bait</p>'+btn(f.claimed?'Claimed':'Claim prize','festival','',f.claimed||f.progress<f.target)+'</div>';}
if(kind==='villagebuild')return Object.entries(LIFE_BUILDINGS).map(([k,d])=>{const b=S.buildings.find(b=>b.type===k);return '<div class="card"><div class="row"><img class="portrait" src="art/life-'+d.sprite+'.webp" alt=""><h2>'+d.name+'</h2></div><p>'+needs(d.need)+(k==='water'?' · or 1 Water Tank':'')+'</p>'+ (b?btn('Open','building',b.id):btn(level()<d.level?'Level '+d.level:'Place · 🪙 '+d.cost,'place',k,level()<d.level||S.coins<d.cost||!has(d.need)&&!(k==='water'&&availableQuantity('water_tank'))))+'</div>';}).join('');
if(kind==='lifeBuilding'){const b=S.buildings.find(b=>b.id===id),d=LIFE_BUILDINGS[b?.type];if(!b||!d)return '';return '<img class="portrait" src="art/life-'+d.sprite+'.webp" alt=""><h2>'+d.name+'</h2>'+(b.ready>now()?'<p>Construction: <span data-time="'+b.ready+'">'+remaining(b.ready)+'</span></p>':d.output?'<p>'+needs(d.input)+'</p><p>Produces '+(d.count+(b.upgrade||0))+' '+ITEMS[d.output].name+'</p>'+(b.lifeEnd?'<p><span data-time="'+b.lifeEnd+'">'+remaining(b.lifeEnd)+'</span></p>'+btn('Collect','lifeCollect',b.id,b.lifeEnd>now()):btn('Start production','lifeStart',b.id,!has(d.input))):'<p>Waters farm fields. Newly planted crops grow '+(10+(b.upgrade||0)*5)+'% faster.</p>')+'<div class="card"><h2>Upgrade '+(b.upgrade||0)+'/2</h2><p>'+needs({plank:4,brick:3})+' · or 1 Workshop Upgrade Kit</p>'+btn('Upgrade · 🪙 '+300*((b.upgrade||0)+1),'workshopUpgrade',b.id,(b.upgrade||0)>=2||b.ready>now()||!!b.lifeEnd||S.coins<300*((b.upgrade||0)+1)||!has({plank:4,brick:3})&&!availableQuantity('workshop_upgrade_kit'))+'</div>'+btn('Move','move',b.id,false,true);}
return '';}

function walkZone(x,y){const v=S.life.visit;if(!v||v.work||x<1||y<1||x>9||y>9)return false;const duration=Math.hypot(x-v.x,y-v.y)*550;v.work={walk:true,x,y,start:now(),end:now()+duration,walkEnd:now()+duration,fromX:v.x,fromY:v.y};change();return true;}

function setFishSpot(k){if(!['river','pond','sea'].includes(k)||S.village.fishing||k==='pond'&&!S.buildings.some(b=>b.type==='ducks'&&b.ready<=now())||k==='sea'&&S.life.explored<6)return false;S.life.fishSpot=k;change();return true;}
function fishingPoint(){const k=S.life?.fishSpot;if(k==='pond'){const b=S.buildings.find(b=>b.type==='ducks');if(b)return {x:b.x+2.1,y:b.y+1};}if(k==='sea')return {x:9.5,y:12.3};return typeof DOCK_SITE!=='undefined'?{x:DOCK_SITE.x+.8,y:DOCK_SITE.y+.4}:{x:6,y:9.1};}
