"use strict";
const VALLEY_GOALS=[{name:'First roots',text:'Plant 8 fields in Sunrise Valley',kind:'fields',target:8,coins:1200},{name:'A new neighbourhood',text:'Move 3 buildings into the valley',kind:'buildings',target:3,coins:1800},{name:'Room to breathe',text:'Clear 12 valley resources',kind:'cleared',target:12,coins:2200},{name:'Valley gardens',text:'Place 6 decorations in the valley',kind:'decor',target:6,coins:1600}];
function valleyProgress(k){if(k==='cleared')return S.resources.filter(r=>inValley(r.x,r.y)&&r.cleared).length;return S[k].filter(o=>inValley(o.x,o.y)).length;}
function claimValley(i){i=+i;const d=VALLEY_GOALS[i];if(!S.eastValley||!d||(S.life.valleyClaims||[]).includes(i)||valleyProgress(d.kind)<d.target)return false;S.life.valleyClaims ||= [];S.life.valleyClaims.push(i);S.coins+=d.coins;give('compost',4);change();return true;}
function valleyGoalsPanel(){return VALLEY_GOALS.map((g,i)=>'<div class="card"><h2>'+g.name+'</h2><p>'+g.text+' · '+Math.min(g.target,valleyProgress(g.kind))+'/'+g.target+'</p>'+btn((S.life.valleyClaims||[]).includes(i)?'Claimed':'Claim '+g.coins+' coins + 4 compost','valleyGoal',i,!S.eastValley||(S.life.valleyClaims||[]).includes(i)||valleyProgress(g.kind)<g.target)+'</div>').join('');}
function homeActivity(arg){const [id,kind]=arg.split(','),c=S.cats.find(c=>c.id===+id);if(!c||!['rest','meal','play'].includes(kind)||c.job&&c.job.end>now())return false;c.homeDays ||= {};if(c.homeDays[kind]===day())return false;if(kind==='meal'&&!has({bread:1,milk:1}))return false;if(kind==='meal')take({bread:1,milk:1});c.homeDays[kind]=day();c.affection=Math.min(100,(c.affection||0)+(kind==='meal'?8:3));c.friendship=Math.min(100,(c.friendship||0)+(kind==='play'?5:2));const h=S.buildings.find(b=>b.type==='house');c.job={kind:'home',label:kind==='meal'?'Eating at home':kind==='rest'?'Resting at home':'Playing at home',target:h.id,x:h.x+2.1,y:h.y+1,end:now()+20000};change();return true;}
function homeCatsPanel(){return '<h2>Cats at home</h2>'+S.cats.map(c=>'<div class="card"><div class="row"><img class="portrait" src="art/biped-'+c.id%4+'.webp" alt=""><div><b>'+safe(c.name)+'</b><p>'+safe(c.job?.kind==='home'?c.job.label:c.job?'Busy on the farm':'Ready to visit')+'</p></div></div><p>Meal: 1 bread + 1 milk. Each activity gives friendship once a day.</p>'+['rest','meal','play'].map(k=>btn(c.homeDays?.[k]===day()?'✓ '+k:k,'homeActivity',c.id+','+k,!!c.job&&c.job.end>now()||c.homeDays?.[k]===day()||k==='meal'&&!has({bread:1,milk:1}),true)).join(' ')+'</div>').join('');}
function contractInfo(){if(S.life.contract?.day!==day()){const pool=Object.keys(RECIPES).filter(k=>canMake(k));const item=pool[Math.floor(now()/86400000)%Math.max(1,pool.length)]||'wheat',count=RECIPES[item]?3:12;S.life.contract={day:day(),item,count,done:false,coins:Math.round(ITEMS[item].value*count*2),xp:Math.min(Math.floor(costXP(level())*.025),300)};saveGame();}return S.life.contract;}
function completeContract(){const c=contractInfo();if(c.done||!has({[c.item]:c.count}))return false;take({[c.item]:c.count});c.done=true;S.coins+=c.coins;gainXP(c.xp);change();return true;}
function contractPanel(){if(!S.life)return "";const c=contractInfo();return '<div class="card"><h2>Village supply order</h2><p>One delivery per day. Supply '+c.count+' '+ITEMS[c.item].name+' for '+c.coins+' coins and '+c.xp+' XP.</p><p>'+needs({[c.item]:c.count})+'</p>'+btn(c.done?'Delivered today':'Deliver supplies','contract','',c.done||!has({[c.item]:c.count}))+'</div>';}
let introStep=0;
const INTRO=[['Welcome to MEW HARVEST','An old farm, a few curious cats, and a whole island to bring to life. Start small and grow your own village.','village-2'],['Grow together','Choose a crop and tap empty fields. One cat manages all fields of the same crop. Harvest, then let helpers carry goods to your barn.','biped-0'],['Make a living village','Feed animals, cook in different kitchens and sell to waiting customers. Clear woodland, build homes and explore across the bridge.','building-0'],['Your island, your way','Drag to explore, pinch to zoom, and hold an object to move it. Open Menu for friendships, cottage activities and your village story.','village-3']];
function introPanel(){const d=INTRO[introStep];return '<div class="welcome"><img src="art/'+d[2]+'.webp" alt=""><p>'+(introStep+1)+' / '+INTRO.length+'</p><h2>'+d[0]+'</h2><p>'+d[1]+'</p>'+btn(introStep===3?'Enter my farm':'Next','introNext')+btn('Skip intro','introSkip','',false,true)+'</div>';}
function finishIntro(){S.introSeen=true;saveGame();closePanel();}
function nextIntro(){if(introStep<3){introStep++;renderPanel();}else finishIntro();}
