'use strict';
// One catalogue owns navigation, search and favourite links.
const FarmNavigation=(()=>{
 const groups=[['farm','🌱','Farm','खेत'],['cats','🐱','Cats','बिल्लियाँ'],['production','⚙','Production','उत्पादन'],['explore','🧭','Explore','खोज'],['stories','📖','Stories','कहानियाँ'],['settings','⚙','Settings','सेटिंग्स']];
 const entries=[
 ['overview','farm','Farm overview','खेत का हाल'],['build','farm','Build & plant','निर्माण और बुवाई'],['island','farm','Expand farm','खेत बढ़ाएँ'],['move','farm','Move objects','जगह बदलें'],['layouts','farm','Layouts & undo','लेआउट और वापस करें'],['map','farm','Farm map','खेत का नक्शा'],
 ['crew','cats','Cat crew','बिल्ली टीम'],['workboard','cats','Work assignments','काम बाँटें'],['hats','cats','Hat shop','टोपी की दुकान'],['friends','cats','Friendship & requests','दोस्ती और अनुरोध'],['memories','cats','Cat memories','बिल्लियों की यादें'],['interior','cats','Cottage interior','घर के अंदर'],
 ['stall','production','Roadside stall','सड़क किनारे दुकान'],['ship','explore','Cargo ship','मालवाहक जहाज़'],['town','stories','Village projects','गाँव की परियोजनाएँ'],['orders','production','Customer orders','ग्राहक ऑर्डर'],['barn','production','Barn & selling','भंडार और बिक्री'],['workshops','production','Workshops','कार्यशालाएँ'],['craft','production','Craft & forest','शिल्प और जंगल'],['planner','production','Production planner','उत्पादन योजना'],['cookbook','production','Recipe book','रेसिपी पुस्तक'],['logistics','production','Tractor & deliveries','ट्रैक्टर और डिलीवरी'],['tools','production','Tools & compost','औज़ार और खाद'],['boutique','production','Island shop','द्वीप की दुकान'],['materials','production','Materials guide','सामग्री गाइड'],
 ['valley','explore','Sunrise Valley · Level 50','सनराइज़ वैली · स्तर 50'],['fishing','explore','Fishing','मछली पकड़ना'],['exploration','explore','Expeditions','अभियान'],['merchant','explore','Merchant boat','व्यापारी नाव'],['coast','explore','Beach visitors','समुद्र तट के मेहमान'],['mountain','explore','Willow mountain','विलो पहाड़'],['collection','explore','Discovery album','खोज संग्रह'],
 ['goals','stories','Next goals','अगले लक्ष्य'],['daily','stories','Daily tasks','रोज़ के काम'],['chapters','stories','Village story','गाँव की कहानी'],['customers','stories','Neighbour stories','पड़ोसियों की कहानियाँ'],['seasons','stories','Seasons & festival','मौसम और उत्सव'],['progress','stories','Village milestones','गाँव की उपलब्धियाँ'],['villagebuild','stories','Village buildings','गाँव की इमारतें'],['restoration','stories','Farm restoration','खेत की मरम्मत'],['market','stories','Shop reputation','दुकान की प्रतिष्ठा'],['journal','stories','Journal','डायरी'],['unlocks','stories','Upcoming unlocks','आगामी सुविधाएँ'],
 ['settings','settings','Preferences & backup','पसंद और बैकअप'],['access','settings','Display & language','डिस्प्ले और भाषा'],['history','settings','Farm activity','खेत का इतिहास'],['release','settings','What’s new','नया क्या है'],['intro','settings','Help & controls','मदद और नियंत्रण']];
 let category='',query='',stack=[],restoring=false;
 function prefs(){S.interface ||= {language:'en',favourites:[],large:false,reduced:false,vibration:false,quality:'high',replant:false,history:[]};return S.interface;}
 function t(en,hi){return prefs().language==='hi'?hi:en;}
 function label(e){return t(e[2],e[3]);}
 function badge(k){const n=k==='workshops'?S.buildings.reduce((n,b)=>n+b.queue.filter(j=>j.end<=now()).length,0):k==='logistics'?S.village?.cargo.filter(q=>!q.done).length:k==='orders'?S.orders.filter(o=>o.arrives<=now()&&has(o.need,o.id)).length:0;return n?`<small class="nav-badge">${n}</small>`:'';}
 function row(e){return `<div class="nav-entry"><button data-action="navGo" data-args="${e[0]}">${safe(label(e))}${badge(e[0])}</button><button class="nav-star" data-action="navPin" data-args="${e[0]}" aria-label="${prefs().favourites.includes(e[0])?'Unpin':'Pin'} ${safe(e[2])}" aria-pressed="${prefs().favourites.includes(e[0])}">${prefs().favourites.includes(e[0])?'★':'☆'}</button></div>`;}
 function menu(){const p=prefs(),q=query.toLowerCase(),filtered=entries.filter(e=>q?(e.join(' ').toLowerCase().includes(q)):e[1]===category);return `<label class="menu-search">${t('Find a feature','सुविधा खोजें')}<input id="menuSearch" type="search" value="${safe(query)}" placeholder="${t('Fishing, hats, backup…','मछली, टोपी, बैकअप…')}" autocomplete="off"></label>`+(!q&&p.favourites.length?`<h2>${t('Favourites','पसंदीदा')}</h2><div class="menu-grid">${p.favourites.map(k=>entries.find(e=>e[0]===k)).filter(Boolean).map(row).join('')}</div>`:'')+(!q?`<div class="nav-categories">${groups.map(g=>`<button data-action="navCategory" data-args="${g[0]}" class="${category===g[0]?'selected':''}">${g[1]} ${t(g[2],g[3])}</button>`).join('')}</div>`:'')+`<div class="menu-grid">${filtered.map(row).join('')}</div>`+(q&&!filtered.length?'<p>'+t('No matching feature. Try another word.','कोई सुविधा नहीं मिली। दूसरा शब्द खोजें।')+'</p>':'');}
 function access(){const p=prefs();return `<p>${t('Language changes the navigation labels and these controls. Recipe and story text remains English.','भाषा मेनू और इन नियंत्रणों पर लागू है। रेसिपी और कहानियाँ अभी अंग्रेज़ी में हैं।')}</p>`+btn(p.language==='hi'?'English':'हिन्दी','navPref','language')+['large','reduced','vibration','replant'].map(k=>btn(({large:t('Large text & controls','बड़ा टेक्स्ट और बटन'),reduced:t('Reduce motion','कम एनिमेशन'),vibration:t('Touch vibration','टच वाइब्रेशन'),replant:t('Offer replant after harvest','कटाई के बाद फिर बोने का विकल्प')})[k]+': '+(p[k]?t('On','चालू'):t('Off','बंद')),'navPref',k,false,true)).join('')+`<h2>${t('Graphics & battery','ग्राफिक्स और बैटरी')}</h2><div class="tabs">${['low','medium','high'].map(k=>btn((p.quality===k?'✓ ':'')+({low:'Low · 30 FPS',medium:'Medium · 45 FPS',high:'High · 60 FPS'})[k],'navQuality',k,false,true)).join('')}</div><p>${t('Low limits effects and water movement. Your progress is unchanged.','Low में इफेक्ट और पानी की गति कम होती है। प्रगति सुरक्षित रहती है।')}</p>`;}
 function apply(){const p=prefs();document.documentElement.classList.toggle('large-controls',!!p.large);document.documentElement.classList.toggle('reduce-motion',!!p.reduced);document.documentElement.lang=p.language==='hi'?'hi':'en';}
 function log(text){const p=prefs();p.history.unshift({at:now(),text:String(text).slice(0,160)});p.history=p.history.slice(0,80);}
 function history(){return '<p>Recent completed actions on this device.</p>'+(prefs().history.length?prefs().history.map(e=>`<div class="card"><small>${new Date(e.at).toLocaleString()}</small><p>${safe(e.text)}</p></div>`).join(''):'<p>Your next completed actions will appear here.</p>');}
 function map(){const a=typeof World!=='undefined'?World.inspect().actors:[],points=[...S.buildings.map(b=>({key:'b'+b.id,x:b.x,y:b.y,name:BUILDINGS[b.type].name,icon:b.type==='store'?'🧺':b.queue.some(j=>j.end<=now())?'✓':'⌂'})),...a.map(c=>({key:'c'+c.id,x:c.x,y:c.y,name:S.cats.find(n=>n.id===c.id)?.name||'Cat',icon:'🐱'}))];if(S.village?.tractor)points.push({key:'tractor',...S.village.tractor,name:'Tractor',icon:'🚜'});const x1=-4,y1=-6,w=S.eastValley?108:48,h=54;return '<p>Tap a marker to visit it. The map shows your unlocked lands.</p><div class="farm-map">'+points.map(p=>`<button class="map-pin" style="left:${Math.max(3,Math.min(95,(p.x-x1)/w*100))}%;top:${Math.max(4,Math.min(93,(p.y-y1)/h*100))}%" data-action="navFocus" data-args="${p.key}" title="${safe(p.name)}" aria-label="${safe(p.name)}">${p.icon}</button>`).join('')+'</div><div class="menu-grid">'+points.map(p=>btn(p.icon+' '+p.name,'navFocus',p.key,false,true)).join('')+'</div>';}
 function focus(key){if(activeZone){notice('Return to your farm first.');return false;}if(key==='tractor'){closePanel();World.followTractor();return true;}const p=key[0]==='b'?S.buildings.find(b=>b.id===+key.slice(1)):World.inspect().actors.find(c=>c.id===+key.slice(1));if(!p)return false;closePanel();World.focus(p.x,p.y);return true;}
 function queuePanel(b){return '<div class="card"><h2>Manage waiting recipes</h2><p>Only recipes that have not started can move or cancel. Cancel returns their ingredients.</p>'+b.queue.map((j,i)=>`<div class="row"><span>${ITEMS[j.item].icon} ${ITEMS[j.item].name}</span>${btn('↑','queueMove',b.id+','+i,i===0||j.start<=now()||b.queue[i-1].start<=now(),true)}${btn('Cancel','queueCancel',b.id+','+i,j.start<=now(),true)}</div>`).join('')+'</div>';}
 function queueEdit(arg,remove){const [id,i]=arg.split(',').map(Number),b=S.buildings.find(b=>b.id===id),j=b?.queue[i];if(!j||j.start<=now())return false;if(!remove&&(i===0||b.queue[i-1].start<=now()))return false;const pending=b.queue.filter(q=>q.start>now()),base=pending[0].start,durations=new Map(pending.map(q=>[q,q.end-q.start]));if(remove){for(const [k,n]of Object.entries(RECIPES[j.item].need))give(k,n);b.queue.splice(i,1);}else [b.queue[i-1],b.queue[i]]=[b.queue[i],b.queue[i-1]];let start=base;for(const q of b.queue){if(!durations.has(q))continue;const duration=durations.get(q);q.start=start;q.end=start+duration;start=q.end;}const c=S.cats.find(c=>c.job?.kind==='cook'&&c.job.target===id);if(c)c.job.end=b.queue.at(-1)?.end||now();log((remove?'Cancelled ':'Reordered ')+ITEMS[j.item].name);change();return true;}
 const originalOpen=openPanel;openPanel=function(type,id=null){if(['village','menu'].includes(type))type='menu';if(type==='wardrobe')type='hats';if(!restoring&&panel&&!(panel===type&&panelId===id)){stack.push({type:panel,id:panelId});if(stack.length>25)stack.shift();}originalOpen(type,id);};
 const originalClose=closePanel;closePanel=function(){stack=[];originalClose();};
 const originalRender=renderPanel;renderPanel=function(){if(!panel)return;const focused=document.activeElement,id=focused?.id,start=focused?.selectionStart;const custom={menu:menu,access,map,history,release:()=>'<h2>MEW HARVEST · 4.0</h2><p>Grouped menu, search, four favourites, map shortcuts, queue editing, replant prompts, activity log and display preferences.</p><p>Your existing farm, purchases and unlocked lands are preserved.</p>'};if(custom[panel]){$('sheetTitle').textContent=({menu:'MEW HARVEST',access:t('Display & language','डिस्प्ले और भाषा'),map:t('Farm map','खेत का नक्शा'),history:t('Farm activity','खेत का इतिहास'),release:t('What’s new','नया क्या है')})[panel];$('sheetBody').innerHTML=custom[panel]();}else{originalRender();if(panel==='building'){const b=S.buildings.find(b=>b.id===panelId);if(b?.queue.length&&!BUILDINGS[b.type].animal)$('sheetBody').insertAdjacentHTML('beforeend',queuePanel(b));}if(panel==='settings'){$('sheetBody').innerHTML=$('sheetBody').innerHTML.replace('v3.2 · Island Stories','v4.0 · Farm Life');$('sheetBody').insertAdjacentHTML('afterbegin','<div class="card">'+btn(t('Display & language','डिस्प्ले और भाषा'),'navGo','access')+btn(t('What’s new','नया क्या है'),'navGo','release',false,true)+'<p>Last saved: '+(S.lastSeen?new Date(S.lastSeen).toLocaleTimeString():'—')+'</p>'+(!prefs().backupAt||now()-prefs().backupAt>7*86400000?'<p>Keep a recent backup before switching devices.</p>':'')+'</div>');}}
 let back=$('menuBack');if(!back){back=document.createElement('button');back.id='menuBack';back.onclick=()=>{const p=stack.pop();if(!p)return;restoring=true;try{openPanel(p.type,p.id)}finally{restoring=false}};$('sheetTitle').before(back);}back.textContent='← '+t('Back','वापस');back.hidden=!stack.length;
 if(id==='menuSearch'){const input=$(id);input?.focus();if(input&&start!==null)input.setSelectionRange?.(start,start);}};
 Object.assign(actions,{navGo:k=>{if(k==='move'){closePanel();World.moveMode();}else openPanel(k);},navCategory:k=>{category=k;query='';renderPanel();},navPin:k=>{const p=prefs();if(p.favourites.includes(k))p.favourites=p.favourites.filter(n=>n!==k);else if(p.favourites.length<4&&entries.some(e=>e[0]===k))p.favourites.push(k);else{notice(t('Choose up to four favourites.','चार पसंदीदा विकल्प चुन सकते हैं।'));return false;}change();return true;},navPref:k=>{const p=prefs();if(k==='language')p.language=p.language==='hi'?'en':'hi';else if(['large','reduced','vibration','replant'].includes(k))p[k]=!p[k];else return false;apply();change();return true;},navQuality:k=>{if(!['low','medium','high'].includes(k))return false;prefs().quality=k;S.life.effects=k!=='low';S.life.waterMotion=k==='high';change();return true;},navFocus:focus,queueCancel:a=>queueEdit(a,true),queueMove:a=>queueEdit(a,false)});
 document.addEventListener('input',e=>{if(e.target.id==='menuSearch'){query=e.target.value;renderPanel();}});
 document.addEventListener('click',e=>{if(prefs().vibration&&e.target.closest('button')&&navigator.vibrate)navigator.vibrate(12);});
 const backup=exportBackup;actions.backup=()=>{backup();prefs().backupAt=now();saveGame();};
 const originalField=fieldAction;fieldAction=function(id){const f=S.fields.find(f=>f.id===id),crop=f?.crop,harvesting=crop&&f.end<=now(),ok=originalField(id);if(ok&&harvesting){log('Harvested '+ITEMS[crop].name);if(prefs().replant){const bar=$('replantPrompt')||document.createElement('div');bar.id='replantPrompt';bar.innerHTML='<span>'+safe(ITEMS[crop].name)+' · '+(CROPS[crop].seedOnly?'1 seed':CROPS[crop].cost+' 🪙')+'</span><button id="replantNow">'+t('Plant again','फिर बोएँ')+'</button><button id="replantClose" aria-label="Dismiss">✕</button>';document.body.append(bar);$('replantClose').onclick=()=>bar.remove();$('replantNow').onclick=()=>{if(f.crop)return bar.remove();const old=S.seed;S.seed=crop;const planted=originalField(id);S.seed=old;saveGame();if(planted)bar.remove();};}}return ok;};
 const originalServe=serve;actions.serve=id=>{const before=S.coins,o=S.orders.find(o=>o.id===+id),ok=originalServe(+id);if(ok&&o){log('Order delivered · '+(S.coins-before)+' coins');saveGame();}return ok;};
 const originalValidate=validate;validate=function(a){const p=a?.interface;if(p&&(!['en','hi'].includes(p.language)||!['low','medium','high'].includes(p.quality)||!Array.isArray(p.favourites)||p.favourites.length>4||p.favourites.some(k=>!entries.some(e=>e[0]===k))||!Array.isArray(p.history)||p.history.length>80||p.history.some(e=>!Number.isFinite(e.at)||typeof e.text!=='string'||e.text.length>160)))return false;return originalValidate(a);};
 apply();return {prefs,log,queueEdit,entries};
})();
