'use strict';
const RESOURCES={grass:{name:'Wild grass',sprite:8,need:1,yield:{fiber:4},cost:5},oak:{name:'Oak',sprite:0,need:3,yield:{wood:5},cost:15},pine:{name:'Pine',sprite:1,need:3,yield:{wood:6},cost:18},birch:{name:'Birch',sprite:2,need:2,yield:{wood:4},cost:12},palm:{name:'Palm',sprite:3,need:2,yield:{wood:4},cost:15},rock:{name:'Stone boulder',sprite:4,need:3,yield:{stone:6},cost:0},ironrock:{name:'Iron deposit',sprite:5,need:4,yield:{stone:3,iron:2},cost:0}};
const CRAFTS={rope:{name:'Rope',need:{fiber:4},give:'rope',count:1},plank:{name:'Wood planks',need:{wood:3},give:'plank',count:2},brick:{name:'Stone blocks',need:{stone:3},give:'brick',count:2},bench:{name:'Garden bench',need:{plank:4,iron:1},give:'bench',count:1},path:{name:'Stone path ×4',need:{stone:2},give:'path',count:4}};
Object.assign(CRAFTS,{claybrick:{name:'Clay bricks ×2',need:{rawclay:3},give:'claybrick',count:2},woodenbeam:{name:'Wooden beams ×2',need:{hardwood:3},give:'woodenbeam',count:2},rooftile:{name:'Roof tiles',need:{rawclay:2},give:'rooftile',count:1},metalhardware:{name:'Metal hardware',need:{ironparts:2},give:'metalhardware',count:1},concreteblock:{name:'Concrete block',need:{brick:2,claybrick:1},give:'concreteblock',count:1}});
function initResources(){S.resources ||= [];S.decor ||= [];S.departures ||= [];S.parcels ||= [];S.houseLevel ??= Math.max(0,Math.ceil((S.cats.length-4)/3));
if(!S.resourceRevision){for(const [i,type] of ['oak','pine','birch','palm','oak','rock','ironrock','rock'].entries()){const x=10+i%4,y=2+Math.floor(i/4)*3;if(!occupied(x,y))S.resources.push({id:S.nextId++,type,x,y,hits:0,end:0,respawn:0});}S.resourceRevision=1;saveGame();}
if(!S.forestOutside){S.resources.forEach((r,i)=>{r.x=-3-Math.floor(i/10)*2;r.y=2+i%10*2;for(const c of S.cats)if(c.job?.target===r.id){c.job.x=r.x+.5;c.job.y=r.y+1.25;}});S.forestOutside=true;saveGame();}
if(!S.outerMeadow){for(let x=-6;x<S.size+6;x+=2)for(let y=-6;y<S.size+6;y+=2){if(x>=0&&y>=0&&x<S.size&&y<S.size||y>=9&&y<=12||!forestSpot(x,y)||S.resources.length>=220)continue;const types=['grass','oak','grass','rock','birch','grass','pine','ironrock','palm'];S.resources.push({id:S.nextId++,type:types[Math.abs(x*7+y*3)%types.length],x,y,hits:0,end:0,respawn:0});}S.outerMeadow=true;}

saveGame();}
initResources();
function migrateRiver(){if(!S.riverRevision){for(const o of [...S.fields,...S.trees,...S.buildings,...S.decor]){if(S.eastValley&&inValley(o.x,o.y))continue;const size=BUILDINGS[o.type]?.size||1;let wet=false;for(let dx=0;dx<size;dx++)for(let dy=0;dy<size;dy++)wet ||= riverBlocked(o.x+dx,o.y+dy);if(!wet)continue;let moved=false;for(let y=0;y<S.size&&!moved;y++)for(let x=0;x<S.size&&!moved;x++)if(!occupied(x,y,size,o.id)){o.x=x;o.y=y;moved=true;for(const c of S.cats)if(c.job?.target===o.id){c.job.x=x+.5;c.job.y=y+size+.25;}}}S.riverRevision=1;saveGame();}

}
migrateRiver();
function workResource(id){const r=S.resources.find(r=>r.id===id);if(!r||r.cleared||!ownedTile(r.x,r.y)&&!(S.eastValley&&inValley(r.x,r.y))||r.end||r.respawn>now())return false;const duration=S.life?Math.max(3000,8000-(S.life.tools[r.type.includes('rock')?'pickaxe':'axe']||0)*1500):8000;const cat=assign(r.type==='grass'?'Cutting grass':r.type.includes('rock')?'Mining':'Chopping',r,now()+duration,r.type.includes('rock')?'mine':'chop');if(!cat)return false;r.end=cat.job.end;change();return true;}
function resourceYield(r){return {...RESOURCES[r.type].yield,...(typeof valleyExtraYield==='function'?valleyExtraYield(r):{})};}
function resourceTick(){let dirty=false;for(const r of S.resources){if(r.cleared)continue;if(r.end&&r.end<=now()){r.end=0;r.hits++;dirty=true;if(r.hits>=RESOURCES[r.type].need){for(const[k,n]of Object.entries(resourceYield(r))){if(S.village&&typeof queueCargo==='function')queueCargo(k,n,r);else give(k,n);}gainXP(4);r.respawn=now()+600000;r.cleared=(S.parcels||[]).includes(parcelKey(r.x,r.y))||!!S.eastValley&&inValley(r.x,r.y);gameNotice(RESOURCES[r.type].name+' collected! Materials collected.');}}if(r.respawn&&r.respawn<=now()){r.respawn=0;r.hits=0;dirty=true;}}if(dirty)change();}
function craftItem(k){if(S.life&&typeof startCraft==='function')return startCraft(k);const r=CRAFTS[k];if(!r||!has(r.need))return false;take(r.need);give(r.give,r.count);change();return true;}
function forestSpot(x,y,ignore=-1){return Number.isInteger(x)&&Number.isInteger(y)&&x>=FARM_GREEN_BOUNDS.x1&&y>=FARM_GREEN_BOUNDS.y1&&x<(S.eastValley?SUNRISE_MAP.x+SUNRISE_MAP.size+8:FARM_GREEN_BOUNDS.x2)&&y<(S.eastValley?Math.max(40,SUNRISE_MAP.y+SUNRISE_MAP.size+8):FARM_GREEN_BOUNDS.y2)&&(x<0||y<0||(x>=S.size||y>=S.size)&&!(S.eastValley&&inValley(x,y)))&&!S.resources.some(r=>r.id!==ignore&&r.x===x&&r.y===y);}
function placeResource(type,x,y){if(!RESOURCES[type]||type.includes('rock')||!forestSpot(x,y)||occupied(x,y,1,-1,true)||S.coins<RESOURCES[type].cost)return false;S.coins-=RESOURCES[type].cost;S.resources.push({id:S.nextId++,type,x,y,hits:0,end:0,respawn:0});change();return true;}
function placeDecor(type,x,y){if(!['bench','path',...Object.keys(DECOR_SHOP)].includes(type)||!availableQuantity(type)||occupied(x,y,DECOR_SHOP[type]?.size||1)||S.decor.some(d=>d.x===x&&d.y===y))return false;take({[type]:1});S.decor.push({id:S.nextId++,type,x,y});change();return true;}
function resourcePanel(id){const r=S.resources.find(r=>r.id===id);if(!r)return '';const d=RESOURCES[r.type],permanent=(S.parcels||[]).includes(parcelKey(r.x,r.y))||S.eastValley&&inValley(r.x,r.y);return '<div class="card"><img class="portrait" src="art/resource-'+d.sprite+'.webp" alt=""><h2>'+d.name+'</h2><p>'+r.hits+'/'+d.need+' jobs complete · each job takes 8s before tool bonuses</p><p>Yields '+Object.entries(resourceYield(r)).map(([k,n])=>n+' '+ITEMS[k].name).join(', ')+'</p>'+btn(r.cleared?'Cleared':r.respawn>now()?'Regrowing · '+remaining(r.respawn):r.end?'Working · '+remaining(r.end):r.type==='grass'?'Cut grass':r.type.includes('rock')?'Mine rock':'Chop tree','resource',id,!!r.cleared||!!r.end||r.respawn>now())+'<p class="muted">'+(permanent?'Clearing permanently releases this tile for your farm.':'Returns after 10 minutes.')+' No tools consumed.</p></div>';}

const SUPPLIES={wheat:{count:10,cost:45},clover:{count:8,cost:65},wood:{count:10,cost:50},stone:{count:10,cost:50},iron:{count:3,cost:45},fiber:{count:12,cost:35},flower:{count:4,cost:72},brick:{count:4,cost:48},plank:{count:4,cost:48},rope:{count:2,cost:36},bait:{count:6,cost:30},compost:{count:4,cost:32}};
if(ITEMS.sunstone)Object.assign(SUPPLIES,{sunstone:{count:2,cost:220,level:50},valleywood:{count:4,cost:180,level:50}});
function buySupply(k){const r=SUPPLIES[k];if(!r||S.coins<r.cost||CROPS[k]?.level>level()||r.level>level())return false;S.coins-=r.cost;give(k,r.count);change();return true;}

function parcelKey(x,y){return Math.floor(x/4)*4+','+Math.floor(y/4)*4;}
function ownedTile(x,y){if(channelTile(x,S,y)||riverBlocked(x,y)||S.eastValley&&(sunriseRiverTile(x,y)||sunriseMountainTile(x,y)))return false;if(!!S.eastValley&&inValley(x,y))return true;if((S.parcels||[]).includes(parcelKey(x,y)))return true;if(typeof World!=='undefined'&&!!World.farmLandAt){const land=World.farmLandAt(x,y);if(land||x<FARM_GREEN_BOUNDS.x1||y<FARM_GREEN_BOUNDS.y1||x>=FARM_GREEN_BOUNDS.x2||y>=FARM_GREEN_BOUNDS.y2)return land;}return x>=0&&y>=0&&x<S.size&&y<S.size;}
function parcelInfo(k){const [x,y]=String(k).split(',').map(Number);const valid=Number.isInteger(x)&&Number.isInteger(y)&&x%4===0&&y%4===0&&x>=-8&&y>=-8&&x+4<=S.size+8&&y+4<=S.size+8;const owned=valid&&Array.from({length:16},(_,i)=>ownedTile(x+i%4,y+Math.floor(i/4))).every(Boolean);const adjacent=valid&&Array.from({length:4},(_,i)=>ownedTile(x-1,y+i)||ownedTile(x+4,y+i)||ownedTile(x+i,y-1)||ownedTile(x+i,y+4)).some(Boolean);return {x,y,valid,owned,adjacent,price:150+(S.parcels?.length||0)*75};}
function availableParcels(){const list=[];for(let x=-8;x<S.size+8;x+=4)for(let y=-8;y<S.size+8;y+=4){const k=x+','+y,d=parcelInfo(k);if(d.valid&&!d.owned&&d.adjacent)list.push({k,...d});}return list;}
function buyParcel(k){const d=parcelInfo(k);if(!d.valid||d.owned||!d.adjacent||S.coins<d.price)return false;S.coins-=d.price;S.parcels.push(k);give('fiber',8);for(const [dx,dy,type]of [[1,1,'rock'],[2,2,'grass']]){const x=d.x+dx,y=d.y+dy;if(!occupied(x,y))S.resources.push({id:S.nextId++,type,x,y,hits:0,end:0,respawn:0});}change();gameNotice('Land unlocked! +8 grass fiber. Clear remaining resources to build.');return true;}
function buyDecoration(k,price=DECOR_SHOP[k]?.cost){const d=DECOR_SHOP[k];if(!d||!Number.isFinite(price)||S.coins<price)return false;S.coins-=price;give(k);change();gameNotice(d.name+' bought. Tap Place to put it on your land.');return true;}
function buyOutfit(args){const[id,k]=args.split(','),c=S.cats.find(c=>c.id===+id),d=OUTFITS[k];if(!c||!d||!c.wardrobe?.includes(k)&&d.level>level())return false;c.wardrobe ||= [];c.outfit ||= {head:null,body:null,neck:null,back:null,accessory:null};c.outfitColors ||= {};if(!c.wardrobe.includes(k)){if(S.coins<d.cost)return false;S.coins-=d.cost;c.wardrobe.push(k);}const slot=d.slot==='hat'?'head':d.slot==='vest'?'body':d.slot;c.outfit[slot]=c.outfit[slot]===k?null:k;if(k==='hat')c.hat=c.outfit[slot]==='hat'?'hat':null;if(k==='vest')c.vest=c.outfit[slot]==='vest'?'vest':null;change();return true;}
function outfitColor(args){const[id,slot]=args.split(','),c=S.cats.find(c=>c.id===+id);if(!c||!['head','body','neck','back','accessory'].includes(slot))return false;c.outfitColors ||= {};const current=c.outfitColors[slot]||'blue',i=OUTFIT_COLORS.indexOf(current);c.outfitColors[slot]=OUTFIT_COLORS[(i+1+OUTFIT_COLORS.length)%OUTFIT_COLORS.length];change();return true;}
function equipOutfitSet(args){const[id,setId]=args.split(','),c=S.cats.find(c=>c.id===+id),set=OUTFIT_SETS[setId];if(!c||!set||Object.values(set.pieces).some(k=>!c.wardrobe?.includes(k)))return false;c.outfit ||= {head:null,body:null,neck:null,back:null,accessory:null};for(const[slot,k]of Object.entries(set.pieces))c.outfit[slot]=k;if(set.pieces.head==='hat')c.hat='hat';if(set.pieces.body==='vest')c.vest='vest';change();return true;}
function shopBuy(k){const d=SHOP_CATALOG[k];if(!d||d.level>level()||S.coins<d.cost)return false;if(d.kind==='seed'){S.seeds ||= {};S.seeds[d.crop]=(S.seeds[d.crop]||0)+d.count;}else if(d.kind==='tree'){S.saplings ||= {};S.saplings[d.tree]=(S.saplings[d.tree]||0)+d.count;}else if(d.kind==='decor')return buyDecoration(d.decor,d.cost);else if(d.kind==='outfit')return buyOutfit(((typeof wardrobeCatId==='number'?wardrobeCatId:S.cats[0]?.id)||0)+','+d.outfit);else if(d.kind==='room')return buyRoomItem(d.room);else if(d.kind==='item')give(d.item,d.count);else return false;S.coins-=d.cost;change();return true;}
function houseCapacity(){return Math.min(12,4+(S.houseLevel||0)*3+S.decor.filter(d=>d.type==='guesthouse').length*2);}
function upgradeHouse(){const price=[400,1200,3000][S.houseLevel||0],kit=availableQuantity('carpenter_kit')>0;if(!price||!kit&&S.coins<price)return false;if(kit)take({carpenter_kit:1});else S.coins-=price;S.houseLevel++;change();gameNotice('Cottage upgraded! Room for '+houseCapacity()+' cats.');return true;}

function rotateDecor(id){const d=S.decor.find(d=>d.id===+id);if(!d||!DECOR_SHOP[d.type])return false;d.flip=!d.flip;change();return true;}
