'use strict';
const $=id=>document.getElementById(id),safe=t=>String(t).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let panel=null,panelId=null,buildTab='farm',shopTab='garden',recipeTab='bakery',wardrobeCatId=0,toastClock,uiSignature='';
let barnQuery='',renderedPanel=null,renderedPanelId=null,noticeVersion=0;
function remaining(t){const n=Math.max(0,Math.ceil((t-now())/1000));return n>=3600?Math.floor(n/3600)+'h '+Math.floor(n%3600/60)+'m':n>=60?Math.floor(n/60)+'m '+n%60+'s':n+'s';}
function notice(text){noticeVersion++;$('toast').textContent=text;$('toast').classList.add('visible');clearTimeout(toastClock);toastClock=setTimeout(()=>$('toast').classList.remove('visible'),2700);}
gameNotice=notice;
const btn=(text,action,args='',disabled=false,secondary=false)=>`<button class="action ${secondary?'secondary':''}" data-action="${action}" data-args="${args}" ${disabled||action==='flowerGift'&&!availableQuantity('flower')||action==='place'&&(DECOR_SHOP[args]||['path','bench'].includes(args))&&!availableQuantity(args)?'disabled':''}>${text}</button>`;
const needs=(n,owner=null)=>Object.entries(n).map(([k,v])=>{const available=typeof usableQuantity==='function'?usableQuantity(k,owner):quantity(k);return `<span class="${available>=v?'good':'missing'}">${ITEMS[k].icon} ${ITEMS[k].name} ${available}/${v}${available<quantity(k)?' available · '+(quantity(k)-available)+' protected':''}</span>`;}).join(' · ');
 function updateHUD(){const l=level();$('level').innerHTML='LV '+l+'<i style="width:'+levelProgress()*100+'%"></i>';$('coins').innerHTML='<span class="coin-symbol" aria-hidden="true">🪙</span>'+S.coins.toLocaleString();$('coins').setAttribute('aria-label',S.coins.toLocaleString()+' coins · Barn');$('crew').textContent='CATS '+S.cats.filter(c=>!c.job||c.job.end<=now()).length+'/'+S.cats.length+' FREE';const g=S.journey&&S.life?nextGoals()[0]:null;$('guide').dataset.open=g?'goals':'overview';$('guide').textContent='NEXT · '+(g?g.text:S.life?nextVillageStep().text:'Tasks · '+Math.round(levelProgress()*100)+'% to next level');const crops=S.fields.filter(f=>f.crop&&f.end<=now()).length,pens=S.buildings.filter(b=>b.fed&&b.fed<=now()).length,food=S.buildings.reduce((n,b)=>n+b.queue.filter(j=>j.end<=now()).length,0);$('farmStatus').textContent=crops+' crops ready · '+pens+' pens ready · '+food+' cooked';const ready=S.orders.filter(o=>o.arrives<=now()&&has(o.need,o.id)).length;$('orderBadge').textContent=ready||'';$('orderBadge').hidden=!ready;}
function renderSeeds(){$('seeds').innerHTML='<div class="tray-title"><b>Choose a crop</b><button data-action="closeSeeds">✕</button></div><div class="seed-list">'+Object.entries(CROPS).map(([k,c])=>{const stock=S.seeds?.[k]||0,access=typeof cropAccess==='function'?cropAccess(k):{ok:c.level<=level()},locked=!access.ok,seedTray=quantity('seed_tray')>0,needsSeed=c.seedOnly&&!stock&&!seedTray;return `<button data-action="seed" data-args="${k}" class="${S.seed===k?'selected':''}" ${locked||needsSeed?'disabled':''}><span>${c.icon}</span>${c.name}<small>${locked?'🔒 '+safe(access.reason||'Lv '+c.level):c.seedOnly?seedTray?'🌱 Seed tray ready':'🌱 Seeds '+stock+' · Shop':'🪙 '+c.cost+' · '+remaining(now()+c.seconds*1000)}</small></button>`}).join('')+'</div><div class="tray-title"><span class="tray-tip">Drag over fields to plant or harvest. Seed packs are reusable farm stock.</span>'+btn('Harvest ready','harvest')+'</div>';}
function openPanel(type,id=null){panel=type;panelId=id;if(type==='materials')shopTab='garden';renderPanel();$('seeds').hidden=true;if(!$('sheet').open)$('sheet').showModal();if(type==='orders'&&id!==null)$('order-'+id)?.scrollIntoView?.({block:'nearest'});}
function closePanel(){panel=null;$('sheet').close();}
function wardrobeSetPanel(c){return '<div class="card outfit-sets"><h2>Matching outfit sets</h2><p>Equip a set after owning all of its pieces.</p><div class="tabs">'+Object.entries(OUTFIT_SETS).map(([k,s])=>{const owned=Object.values(s.pieces).every(p=>c.wardrobe?.includes(p)),active=owned&&Object.entries(s.pieces).every(([slot,p])=>c.outfit?.[slot]===p);return btn((active?'✓ ':'')+s.name,'outfitSet',c.id+','+k,!owned,true)}).join('')+'</div></div>';}
function renderPanel(){if(!panel)return;
 const samePanel=renderedPanel===panel&&renderedPanelId===panelId,body=$('sheetBody'),focused=document.activeElement;
 if(samePanel&&body.contains?.(focused)&&['range','file'].includes(focused.type))return;
 const savedInputs=samePanel?['layoutName','barnSearch'].map(id=>{const input=$(id);return input?{id,value:input.value,focused:focused===input,start:input.selectionStart,end:input.selectionEnd}:null;}).filter(Boolean):[];
 let title='',html='';const l=level();
if(S.journey&&['goals','memories','customers','seasons','layouts','layoutPreview'].includes(panel)){title={goals:'Next Goals',memories:'Cat memories',customers:'Neighbour stories',seasons:'Seasonal market',layouts:'Farm layouts',layoutPreview:'Layout preview'}[panel];html=journeyPanel(panel,panelId);}
if(panel==='materials'){title='Materials & Flowers';html=materialsPanel();}
if(panel==='unlocks'){title='Upcoming Unlocks';html=upcomingPanel();}
if(panel==='hats'){title='Hat shop';html=HatShop.panel();}
if(panel==='planner'){title='Production Planner';html=plannerPanel();}
if(['chapters','friends','cookbook'].includes(panel)){title={chapters:'Village story',friends:'Cat friendships',cookbook:'Recipe book'}[panel];html=communityPanel(panel);}
if(panel==='coast'){title='Beach visitors';html=coastPanel();}
if(panel==='intro'){title='MEW HARVEST';html=introPanel();}
if(panel==='valley'){title='Sunrise Valley';html=valleyPanel()+valleyGoalsPanel();}
if(panel==='mountain'){title='Willow mountain';html=mountainPanel()+btn('View mountain','goMountain','',false,true);}
if(['overview','market'].includes(panel)){title=panel==='overview'?'Farm overview':'Shop reputation';html=managementPanel(panel);}
if(['progress','tools','interior','workboard','collection','festival','villagebuild','lifeBuilding'].includes(panel)){title={progress:'Village milestones',tools:'Tools & compost',interior:'Inside the cottage',workboard:'Cat work board',collection:'Discovery book',festival:'Village festival',villagebuild:'Village buildings',lifeBuilding:'Village building'}[panel];html=lifePanel(panel,panelId);}
if(['village','restoration','fishing','exploration','merchant','logistics'].includes(panel)){title={village:'Your village',restoration:'Farm restoration',fishing:'River fishing',exploration:'Exploration',merchant:'Merchant boat',logistics:'Goods deliveries'}[panel];html=villagePanel(panel);}
if(panel==='menu'){title='MEW HARVEST';html='<div class="menu-grid">'+[['logistics','🚜 Tractor & deliveries'],['coast','🌊 Beach visitors'],['intro','🐾 Welcome guide'],['interior','🏠 Inside the cottage'],['valley','🌄 Sunrise Valley · Lv 50'],['chapters','📖 Village story'],['friends','💛 Cat friendships'],['cookbook','🍽 Recipe book'],['overview','📋 Farm overview'],['market','⭐ Shop reputation'],['village','🌿 Living village'],['boutique','🛍 Island shop'],['barn','🧺 Barn'],['crew','🐱 Cat crew'],['build','🏡 Build & plant'],['workshops','🍳 Workshops'],['craft','🪵 Craft & forest'],['move','↔ Move things'],['daily','🎁 Daily tasks'],['journal','📖 Journal'],['island','🏝️ Expand island'],['settings','⚙ Settings']].map(([k,t])=>`<button ${k==='move'?'data-action="moveMode"':`data-open="${k}"`}>${t}</button>`).join('')+'</div>';}
if(panel==='orders'){
 title='Island store';html='<p class="intro">Serve any waiting customer whose goods are in your barn. You can skip ahead; everyone else keeps waiting. Collected goods must finish delivery first.</p>'+
 S.orders.map(o=>o.arrives>now()?`<div class="card"><h2>🐾 A customer is on the way</h2><span data-time="${o.arrives}">${remaining(o.arrives)}</span></div>`:
   `<div id="order-${o.id}" class="card order-card ${panelId===o.id?'selected-order':''}"><div class="row"><h2>${o.special?'⭐':'🐱'} ${safe(o.name)}</h2><b>🪙 ${typeof orderPayment==='function'?orderPayment(o):o.reward}</b></div>${S.journey?.reserved.includes(o.id)?'<p>🔒 Stock protected for this customer</p>':''}${typeof customerBonus==='function'&&customerBonus(o)?'<p>Returning neighbour · '+customerBonus(o)+'% friendship tip</p>':''}<p>${needs(o.need,o.id)}</p><div class="row">${btn('Deliver · '+o.xp+' XP','serve',o.id,!has(o.need,o.id))}${btn('Plan','planOrder',o.id,false,true)}${btn('Dismiss','dismiss',o.id,false,true)}</div></div>`).join('');
 html+=contractPanel()+'<button data-open="boutique">🛍 Island shop</button><div class="card"><h2>Store expansion</h2><p>'+S.orders.length+' customer spaces</p>'+btn(S.storeLevel>=3?'Fully expanded':'Add 2 spaces · 🪙 '+[1000,5000,15000][S.storeLevel],'store','',S.storeLevel>=3||S.coins<[1000,5000,15000][S.storeLevel])+'</div>';
}
if(panel==='decoration'){const d=S.decor.find(d=>d.id===panelId);title=DECOR_SHOP[d?.type]?.name||'Decoration';html=(d?gardenPanel(d):'')+btn('Move','move',panelId)+' '+btn('Rotate','rotate',panelId,!DECOR_SHOP[d?.type],true)+' '+btn('Store in barn','decorStore',panelId,false,true);}
if(panel==='boutique'){if(['clothing','accessories'].includes(shopTab))shopTab='garden';title='Island shop';const categories=[['garden','Decorations'],['seasonal','Seasonal'],['seeds','Seeds & Crops'],['trees','Trees & Plants'],['materials','Materials'],['animal','Animal Care'],['fishing','Fishing'],['tools','Tools'],['transport','Transport'],['exploration','Exploration'],['furniture','Furniture']];html='<p class="intro">Farm coins only · 🪙 '+S.coins.toLocaleString()+' available. Every purchase is placeable, plantable, craftable or usable.</p><div class="tabs"><button data-open="supplies">Quick supplies</button><button data-open="island">Land</button><button data-open="crew">Cottage</button></div><div class="tabs">'+categories.map(([k,n])=>btn((shopTab===k?'✓ ':'')+n,'shopTab',k,false,true)).join('')+'</div>'+(['garden','seasonal','transport'].includes(shopTab)?'<div class="grid">'+Object.entries(DECOR_SHOP).filter(([k])=>shopCategory(k)===shopTab).map(([k,d])=>'<div class="card shop-card"><img class="portrait" src="art/'+(d.art||'shop-'+d.sprite)+'.webp" alt=""><h2>'+d.name+'</h2><p>'+(d.description||'A decorative item for your island.')+'</p><p>'+quantity(k)+' in barn</p>'+btn('Buy · 🪙 '+d.cost,'decorBuy',k,S.coins<d.cost)+' '+btn('Place','place',k,!quantity(k),true)+'</div>').join('')+'</div>':'<div class="grid">'+Object.entries(SHOP_CATALOG).filter(([,d])=>d.category===shopTab).map(([k,d])=>{const owned=d.kind==='seed'?(S.seeds?.[d.crop]||0):d.kind==='tree'?(S.saplings?.[d.tree]||0):d.kind==='item'?quantity(d.item):d.kind==='decor'?quantity(d.decor):d.kind==='room'?S.life?.room?.owned?.includes(d.room)?1:0:0;const locked=d.level>level();return '<div class="card shop-card"><div class="shop-icon">'+d.icon+'</div><h2>'+d.name+'</h2><p>'+d.purpose+'</p><p>'+(locked?'Unlocks at level '+d.level:'Owned: '+owned)+(d.kind==='seed'?' seeds':d.kind==='tree'?' saplings':'')+'</p>'+btn(locked?'🔒 Level '+d.level:'Buy ×'+d.count+' · 🪙 '+d.cost,'shopBuy',k,locked||S.coins<d.cost)+'</div>';}).join('')+'</div>'); }
if(panel==='wardrobe'){title='Cat appearance';html='<p>Cats use their original painted appearance. Your previously purchased items remain saved.</p>'+S.cats.map(c=>'<div class="card"><img class="portrait" src="art/biped-'+c.id%4+'.webp" alt="Cat"><b>'+safe(c.name)+'</b></div>').join('');}

if(panel==='parcel'){const d=parcelInfo(panelId);title='Meadow plot';html='<div class="card"><h2>Unlock 4 × 4 tiles</h2><p>Clear the tall grass and uncover stone. Includes 8 grass fiber. Trees and rocks can be collected after unlocking.</p>'+btn('Unlock · 🪙 '+d.price,'parcel',panelId,d.owned||!d.adjacent||S.coins<d.price)+'</div>'; }
if(panel==='supplies'){title='Quick supply shop';html='<p class="intro">Common farm staples. For the complete organized catalog, open the Shop categories.</p><div class="grid">'+Object.entries(SUPPLIES).map(([k,r])=>'<div class="card"><div class="icon">'+ITEMS[k].icon+'</div><h2>'+ITEMS[k].name+' ×'+r.count+'</h2><p>In barn: '+quantity(k)+'</p>'+btn(r.level>level()?'Level '+r.level:'Buy · 🪙 '+r.cost,'supply',k,S.coins<r.cost||CROPS[k]?.level>level()||r.level>level())+'</div>').join('')+'</div>';}
if(panel==='barn'){title='Your barn';const entries=Object.entries(S.inventory).filter(([k,n])=>n>0);html='<p class="intro">Keep ingredients for recipes and orders, or sell extra goods. Protected order stock stays in your barn.</p><label class="input-label">Find goods<input id="barnSearch" type="search" placeholder="Search crops, materials, recipes…" value="'+safe(barnQuery)+'"></label><div class="grid">'+entries.map(([k,n])=>{const available=typeof usableQuantity==='function'?usableQuantity(k):n;return `<div class="card" data-barn-name="${safe(ITEMS[k].name.toLowerCase())}" ${ITEMS[k].name.toLowerCase().includes(barnQuery)?'':'hidden'}><div class="icon">${ITEMS[k].icon}</div><h2>${ITEMS[k].name} ×${n}</h2><p>🪙 ${ITEMS[k].value} each${available<n?' · 🔒 '+(n-available)+' protected':''}</p>${btn('Sell 1','sell',k,!available)} ${btn('Sell spare','sellAll',k,!available,true)}</div>`;}).join('')+'</div>'+(entries.length?'':'<p>Your barn is empty. Harvest some wheat.</p>');}
if(panel==='crew'){title='Cat crew';html='<p class="intro">Cats walk to their work. One cat manages all growing fields of the same crop. Different crops use different cats. Cats become free when their crop ripens. Cooking keeps a cat until the queue finishes.</p>'+S.cats.map(c=>`<div class="card row"><img class="portrait" src="art/biped-${c.id%4}.webp" alt=""><div><h2>${safe(c.name)}</h2><small>${safe(c.personality||PERSONALITIES[c.id%4])} · ♥ ${c.affection||0} · ${c.experience||0} deliveries · ${c.friendship||0} friendship</small><br><span>${c.job&&c.job.end>now()?safe(c.job.label)+' · <span data-time="'+c.job.end+'">'+remaining(c.job.end)+'</span>':'Ready to help'}</span><p>${personalityBenefit(c)}</p>${btn('Say hello','pet',c.id,c.petted===day(),true)}${btn('Give flower · +8 affection','flowerGift',c.id,!quantity('flower')||c.flowerDay===day(),true)}</div></div>`).join('');const housePrice=[400,1200,3000][S.houseLevel||0],houseKit=availableQuantity('carpenter_kit')>0;html+='<div class="card"><h2>Cat cottage · Level '+((S.houseLevel||0)+1)+'</h2><p>Room for '+houseCapacity()+' cats · '+S.cats.length+' living here</p><p>Upgrade with 🪙 '+housePrice+' or 1 Carpenter Kit.</p>'+btn(S.houseLevel>=3?'Fully upgraded':'Upgrade cottage','houseUpgrade','',S.houseLevel>=3||(!houseKit&&S.coins<housePrice))+'<button data-open="wardrobe">Clothes & hats</button></div>';const n=S.cats.length;html+='<div class="card"><h2>Welcome a helper</h2><p>Unlock at level '+(n-1)+'</p>'+btn(n>=houseCapacity()?'Upgrade cottage for more cats':'Recruit · 🪙 '+100*(n-2)**2,'recruit','',n>=houseCapacity()||l<n-1||S.coins<100*(n-2)**2)+'</div>';}
if(panel==='build'){
 title='Build your island';html='<div class="tabs">'+[['farm','Farm'],['animals','Animals'],['kitchens','Kitchens'],['trees','Trees']].map(([k,n])=>`<button class="${k===buildTab?'active':''}" data-action="tab" data-args="${k}">${n}</button>`).join('')+'</div>';
 if(buildTab==='farm')html+='<div class="card"><h2>🌱 Growing field</h2><p>'+S.fields.length+'/'+fieldLimit()+' fields available at your level.</p>'+btn('Place · 🪙 10','place','field',S.coins<10||S.fields.length>=fieldLimit())+'</div>';
 else if(buildTab==='trees')html+=Object.entries(TREES).map(([k,d])=>{
  const stock=(S.saplings?.[k]||0)+availableQuantity('sapling_'+k),access=typeof cropAccess==='function'?cropAccess(k):{ok:l>=d.level,reason:'Unlocks at level '+d.level+'.'};
   return `<div class="card"><h2>${d.icon} ${d.name}</h2><p>Water, then collect 3 fruit. The tree stays. Place on any buildable ground, including Main Farm.</p><p>${stock} saplings available</p>${btn(!access.ok?safe(access.reason):stock?'Plant owned sapling':'Place · 🪙 '+d.cost,'place',k,!access.ok||!stock&&S.coins<d.cost)}</div>`;
 }).join('');
 else html+=Object.entries(BUILDINGS).filter(([k,d])=>buildTab==='animals'?d.animal:!d.animal&&!d.life&&!['store','house'].includes(k)&&!d.project).map(([k,d])=>{const owned=S.buildings.find(b=>b.type===k);return `<div class="card"><div class="row"><img class="portrait" src="art/${d.art||'building-'+d.sprite}.webp" alt=""><div><h2>${d.name}</h2><p>${d.animal?'Build a pen, then welcome animals.':'Upgradeable production slots · a working cat needed.'}</p></div></div>${owned?btn('Open building','building',owned.id,false,true):btn(l<d.level?'🔒 Level '+d.level:'Place · 🪙 '+d.cost,'place',k,l<d.level||S.coins<d.cost)}</div>`;}).join('');
}
if(panel==='building'){
 const b=S.buildings.find(b=>b.id===panelId);if(!b)return closePanel();const d=BUILDINGS[b.type];
 if(d.life)return openPanel('lifeBuilding',b.id);if(b.type==='store')return openPanel('orders');if(b.type==='house')return openPanel('crew');
 title=d.name;html='<div class="row"><img class="portrait" src="art/'+buildingArt(b.type)+'.webp" alt=""><p class="intro">'+(d.animal?'A home for your animals.':'Made here on your island.')+'</p></div>';
 if(b.ready>now())html+='<div class="card"><h2>🔨 Under construction</h2><p>Ready in <span data-time="'+b.ready+'">'+remaining(b.ready)+'</span></p></div>';
 else if(d.animal){
  html+='<div class="card"><h2>'+animalRoutine(b)+'</h2><p>Happiness '+(b.happiness||0)+'/100 · 60+ gives a bonus product.</p>'+btn('Care & fresh water','care',b.id,b.cared===day())+'</div>';
    html+='<div class="card"><h2>'+d.animal+' '+b.animals+'/4 animals</h2><p>'+(b.fed?b.fed>now()?'Resting · <span data-time="'+b.fed+'">'+remaining(b.fed)+'</span>':'Products ready!':needs({[d.feed]:b.animals||1})+' · Hay '+availableQuantity('hay_bale'))+'</p>'+btn(b.fed?'Collect '+ITEMS[d.product].icon:'Feed all','feed',b.id,!b.animals||b.fed>now()||!b.fed&&!has({[d.feed]:b.animals})&&!has({hay_bale:b.animals}))+' '+btn('Premium feed','premiumFeed',b.id,!b.animals||!!b.fed||!has({premium_feed:b.animals}),true)+'</div>';
  html+='<div class="card"><h2>Welcome another animal</h2>'+btn('🪙 '+d.animalCost*(1+b.animals),'animal',b.id,b.animals>=4||!!b.fed||S.coins<d.animalCost*(1+b.animals))+'<p class="muted">Animals can join while the pen is waiting for feed.</p></div>';
 }else{
  html+='<div class="queue">'+Array.from({length:3+(b.upgrade||0)},(_,i)=>{const j=b.queue[i];return '<div class="slot '+(j?'filled':'')+'">'+(j?'<b>'+ITEMS[j.item].icon+'</b>'+(j.end<=now()?'Ready':j.start>now()?'Queued':'<span data-time="'+j.end+'">'+remaining(j.end)+'</span>'):'Empty slot')+'</div>';}).join('')+'</div>'+btn('Collect finished','collect',b.id,!b.queue.some(j=>j.end<=now()));
   html+='<div class="grid" style="margin-top:14px">'+Object.entries(RECIPES).filter(([k,r])=>r.at===b.type).map(([k,r])=>'<div class="card"><div class="icon">'+ITEMS[k].icon+'</div><h2>'+ITEMS[k].name+'</h2><p>'+needs(r.need)+'</p><p class="muted">'+remaining(now()+r.time*1000)+'</p>'+btn(r.festival&&!S.journey?.learned.includes(k)?'Learn at seasonal market':!recipeUnlocked(k)?'🔒 Lv '+Math.max(r.level,d.level):'Cook','cook',b.id+','+k,!recipeUnlocked(k)||b.queue.length>=3+(b.upgrade||0)||!has(r.need))+(r.festival&&!S.journey?.learned.includes(k)?'<button data-open="seasons">Learn recipe</button>':'')+'</div>').join('')+'</div>';
 }
  if(d.animal){const u=penUpgradeInfo(b);html+='<div class="card"><h2>Animal home level '+(u.level+1)+'</h2><p>Each upgrade adds one product per collection and speeds up the next feeding cycle.</p><p>'+needs(u.need)+' · or 1 Maintenance Kit</p>'+btn(u.level>=2?'Fully upgraded':'Upgrade · 🪙 '+u.coins,'penUpgrade',b.id,u.level>=2||!!b.fed||b.ready>now()||S.coins<u.coins||!has(u.need)&&!availableQuantity('maintenance_kit'))+'</div>';}
  else html+='<div class="card"><h2>Workshop level '+(1+(b.upgrade||0))+'</h2><p>Upgrade adds a queue slot and faster cooking. '+needs({plank:4,brick:3})+' · or 1 Workshop Upgrade Kit</p>'+btn((b.upgrade||0)>=2?'Fully upgraded':'Upgrade · 🪙 '+300*((b.upgrade||0)+1),'workshopUpgrade',b.id,(b.upgrade||0)>=2||b.queue.length>0||b.ready>now()||S.coins<300*((b.upgrade||0)+1)||!has({plank:4,brick:3})&&!availableQuantity('workshop_upgrade_kit'))+'</div>';
 html+='<div style="margin-top:15px">'+btn('Move building','move',b.id,false,true)+'</div>';
}
if(panel==='workshops'){title='Production workshops';const list=S.buildings.filter(b=>!BUILDINGS[b.type].animal&&!['house','store'].includes(b.type)&&!BUILDINGS[b.type].project);html=list.map(b=>`<div class="card row"><img class="portrait" src="art/${buildingArt(b.type)}.webp" alt=""><div><h2>${BUILDINGS[b.type].name}</h2><p>${BUILDINGS[b.type].life?(b.lifeEnd?(b.lifeEnd<=now()?'Ready to collect':'Producing'):'Ready to start'):b.queue.length+'/'+(3+(b.upgrade||0))+' slots used'}</p>${btn('Open','building',b.id)}</div></div>`).join('')+btn('Build a workshop','openBuild');}
if(panel==='daily'){title='Daily tasks';html='<div class="card"><h2>🎁 A gift for your farm</h2><p>50 coins and 3 wheat, once each day.</p>'+btn(S.daily.gift?'Collected today':'Collect gift','gift','',S.daily.gift)+'</div>'+DAILY_TASKS.map(t=>{const n=Math.min(t.total,taskProgress(t)),done=S.daily.claimed.includes(t.id);return '<div class="card"><h2>'+t.name+'</h2><p>'+n+'/'+t.total+' · 🪙 '+t.reward+'</p><div class="progress"><i style="width:'+n/t.total*100+'%"></i></div>'+btn(done?'Claimed':'Claim reward','task',t.id,done||n<t.total)+'</div>'}).join('');}
if(panel==='island'){title='Unlock meadow land';html='<p class="intro">Buy one small plot at a time. Each plot opens 4 × 4 tiles beside your land. Your existing farm stays yours.</p>'+availableParcels().map(d=>'<div class="card"><h2>Meadow '+d.x+', '+d.y+'</h2><p>Grass clearing · 16 tiles · +8 fiber</p>'+btn('View plot','viewParcel',d.k,false,true)+' '+btn('Unlock · 🪙 '+d.price,'parcel',d.k,S.coins<d.price)+'</div>').join('');}
if(panel==='journal'){title='Island journal';const g=goal();html='<div class="card"><h2>'+g.text+'</h2><div class="progress"><i style="width:'+Math.min(100,g.n/g.total*100)+'%"></i></div><p>Level '+l+' · '+Math.floor(levelProgress()*100)+'% to next level</p></div><div class="grid">'+[['🌾 Harvests',S.stats.harvest],['✓ Orders served',S.stats.served],['🍳 Products cooked',S.stats.cooked],['🥚 Animal goods',S.stats.animals]].map(([n,v])=>`<div class="card"><h2>${n}</h2><b>${v}</b></div>`).join('')+'</div><h2 style="font-size:18px;margin:18px 0">Next discoveries</h2>'+Object.entries(BUILDINGS).filter(([k,d])=>d.level>l).slice(0,4).map(([k,d])=>`<div class="card">Level ${d.level} · ${d.name}</div>`).join('')+'<p class="intro">Harvests never spoil. Growing, animal and kitchen timers continue while you are away.</p>';}
if(panel==='resource'){title='Island resources';html=resourcePanel(panelId);}
if(panel==='craft'){title='Craft & forest';html=craftingPanel()+'<p class="intro">Unlock meadow plots with coins, then tap trees, grass and rocks to gather materials with a free cat.</p>'+btn('Go to woodland','forest')+Object.entries(CRAFTS).map(([k,r])=>'<div class="card"><h2>'+r.name+'</h2><p>'+needs(r.need)+'</p>'+btn('Craft · '+(CRAFT_DURATIONS[k]||15)+'s','craft',k,!has(r.need)||(S.life?.crafting||[]).length>=3)+(['bench','path'].includes(k)?' '+btn('Place · '+quantity(k)+' owned','place',k,!quantity(k),true):'')+'</div>').join('')+'<h2>Plant outside your farm</h2>'+Object.entries(RESOURCES).filter(([k])=>!k.includes('rock')).map(([k,r])=>'<div class="card row"><img class="portrait" src="art/resource-'+r.sprite+'.webp" alt=""><div><h2>'+r.name+'</h2>'+btn('Plant · 🪙 '+r.cost,'place',k,S.coins<r.cost)+'</div></div>').join('');}
if(panel==='settings'){title='Settings';html='<p class="intro">MEW HARVEST · v3.1 reconstruction + Production Planner</p><div class="card"><h2>Save your island</h2><p>Progress is stored in this browser. Add MEW HARVEST to your home screen from your browser menu; after the game has loaded, cached content can work offline. Download a backup before switching devices or clearing browser data.</p>'+btn('Download backup','backup')+'<label class="action secondary file-label">Restore backup<input id="restore" type="file" accept="application/json,.json"></label><p class="muted">'+(saveError?'Browser saving failed. Download a backup now.':'Saved on this device.')+'</p></div><div class="card"><h2>Island preferences</h2>'+btn(S.details?'Hide field timers':'Show field timers','details','',false,true)+' '+btn(S.life?.effects?'Weather effects on':'Weather effects off','effects','',false,true)+' '+btn(S.life?.waterMotion===false?'River motion off':'River motion on','waterMotion','',false,true)+' '+btn(S.sound?'Sound on':'Sound off','sound','',false,true)+'</div><div class="card"><h2>Controls</h2><p>Drag grass to explore. Pinch or use +/− to zoom. Tap a ripe crop to collect it. Drag over a row to farm several fields. Tap buildings to use them. Hold a field, building, tree or decoration for half a second, drag it, and release to move it.</p></div>'+btn('Centre camera','center','',false,true);}
if(['menu','overview','orders','workshops'].includes(panel))html='<button class="action secondary full" data-open="planner">Production Planner</button>'+html;
if(['boutique','crew','wardrobe'].includes(panel))html='<button class="action secondary full" data-open="hats">🎩 Hat shop · choose a cat</button>'+html;
if(['menu','boutique','supplies','craft'].includes(panel))html='<button class="action secondary full" data-open="materials">Materials & Flowers guide</button>'+html;
if(['menu','journal','overview','build'].includes(panel))html='<button class="action secondary full" data-open="unlocks">Upcoming Unlocks</button>'+html;
 if(['overview','workshops','barn'].includes(panel))html='<div class="card">'+btn('Collect All · '+readyGoods()+' ready','collectAll','',!readyGoods())+'<p>Includes fields, fruit, pens, kitchens, village goods, flowers and crafts. Helpers deliver to the barn.</p></div>'+html;
 if(S.journey){
  if(panel==='menu')html='<div class="menu-grid journey-menu">'+[['goals','🎯 Next Goals'],['memories','🐱 Cat memories'],['customers','💬 Neighbour stories'],['layouts','🏡 Farm layouts'],['seasons','🌸 Seasonal market']].map(([k,t])=>'<button data-open="'+k+'">'+t+'</button>').join('')+'</div>'+html;
  if(panel==='overview')html='<h2>Your next three goals</h2>'+goalsPanel(true)+'<button class="action secondary full" data-open="layouts">Farm layout presets & undo</button>'+html;
  if(['crew','friends','interior'].includes(panel))html='<button class="action secondary full" data-open="memories">Favourite treats & friendship memories</button>'+html;
  if(panel==='orders')html='<button class="action secondary full" data-open="customers">Returning-neighbour stories</button>'+html;
  if(panel==='valley')html+=valleyProjectsPanel();
  if(panel==='festival')html+='<h2>Seasonal market</h2>'+seasonalMarketPanel();
  if(panel==='settings')html=html.replace('v3.1 reconstruction + Production Planner','v3.2 · Island Stories')+audioSettingsPanel();
  if(panel==='wardrobe')html=html.replaceAll('Level 101 · ','Friendship reward · ').replaceAll('Buy & equip · 🪙 0','Earn through friendship');
 }
  if(panel==='settings'&&recoveryBackup)html='<div class="card"><h2>Preserved save</h2><p>A previous save could not be loaded. Its original data has been kept so it can be recovered.</p>'+btn('Download preserved save','backupRecovery')+'</div>'+html;
  $('sheetTitle').textContent=title;body.innerHTML=html;renderedPanel=panel;renderedPanelId=panelId;
  if(panel==='hats')HatShop.previews();
  if(panel==='wardrobe'&&typeof World!=='undefined'&&World.wardrobePreview)World.wardrobePreview($('outfitPortrait'),S.cats.find(c=>c.id===wardrobeCatId)||S.cats[0]);
  for(const state of savedInputs){const input=$(state.id);if(!input)continue;input.value=state.value;if(state.focused){input.focus({preventScroll:true});try{input.setSelectionRange(state.start,state.end);}catch{}}}
}
function exportBackup(){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'}));a.href=url;a.download='MEW-HARVEST-Backup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportRecoveryBackup(){if(!recoveryBackup)return false;const a=document.createElement('a'),url=URL.createObjectURL(new Blob([recoveryBackup],{type:'application/json'}));a.href=url;a.download='MEW-HARVEST-Preserved-Save.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);return true;}
const actions={hatBuy:k=>HatShop.buy(k),hatCat:id=>HatShop.select(id),hatWear:a=>HatShop.wear(a),tractorToggle:()=>CargoTransport.toggle(),tractorFollow:()=>{closePanel();World.followTractor();},coastMeet:greetCoast,goCoast:()=>{closePanel();World.coast()},introNext:nextIntro,introSkip:finishIntro,valleyGoal:claimValley,homeActivity,contract:completeContract,unlockValley,goValley:()=>{closePanel();World.valley()},recipeTab:k=>{recipeTab=k;renderPanel()},chapter:claimChapter,catRequest:completeCatRequest,bond:claimBond,roomBuy:buyRoomItem,roomPlace:placeRoomItem,goMountain:()=>{closePanel();World.mountain()},gardenUse:useGarden,decorStore:id=>{if(!storeDecoration(id))return false;openPanel('boutique');return true},flowerGift:giftFlower,shopTab:k=>{shopTab=k;renderPanel()},craftCollect:collectCrafts,waterMotion:()=>{S.life.waterMotion=S.life.waterMotion===false;change()},penUpgrade:upgradePen,discovery:claimDiscovery,cargoFirst:prioritizeCargo,animalTab:()=>{buildTab='animals';openPanel('build')},fishSpot:setFishSpot,visit:k=>{if(!visitZone(k))return false;closePanel();World.enterZone();return true},milestone:claimMilestone,tool:upgradeTool,fertilize:fertilizeFields,care:careAnimals,lifeStart:startLifeProduction,lifeCollect:collectLifeProduction,furnish:furnishHouse,role:chooseRole,festival:claimFestival,effects:()=>{S.life.effects=!S.life.effects;change()},restoreFarm,pier:buildPier,fish:startFishing,fishCollect:reelBonus,rod:upgradeRod,trip:startExpedition,tripClaim:claimExpedition,boat:tradeBoat,workshopUpgrade:upgradeWorkshop,pet:petCat,goPier:()=>{closePanel();World.pier()},rotate:rotateDecor,decorBuy:buyDecoration,outfit:buyOutfit,houseUpgrade:upgradeHouse,parcel:buyParcel,viewParcel:k=>{closePanel();World.parcel(k)},supply:buySupply,forest:()=>{closePanel();World.forest()},resource:id=>workResource(+id),craft:craftItem,task:claimTask,details:()=>{S.details=!S.details;change()},sound:()=>{S.sound=!S.sound;change();playTone()},closeSeeds:()=>{$('seeds').hidden=true},seed:k=>{S.seed=k;change();renderSeeds()},harvest:harvestAll,serve:id=>serve(+id),dismiss:id=>dismiss(+id),sell:k=>sellItem(k),sellAll:k=>sellItem(k,quantity(k)),recruit,gift:dailyGift,store:upgradeStore,expand:expandIsland,tab:k=>{buildTab=k;renderPanel()},place:k=>{closePanel();World.placing(k)},building:id=>openPanel('building',+id),feed:id=>feedAnimal(+id),animal:id=>buyAnimal(+id),cook:a=>{const[id,k]=a.split(',');return cook(+id,k)},collect:id=>collectKitchen(+id),move:id=>{closePanel();World.moving(+id)},moveMode:()=>{closePanel();World.moveMode()},openBuild:()=>{buildTab='kitchens';openPanel('build')},backup:exportBackup,center:()=>{closePanel();World.center()}};
actions.collectAll=collectAll;
actions.goVolcano=()=>{closePanel();World.volcano();};
actions.goBridge=()=>{closePanel();World.bridge();};
actions.goIslands=()=>{closePanel();World.islands();};
actions.backupRecovery=exportRecoveryBackup;
Object.assign(actions,{planOrder,planToggle:togglePlanOrder,planAll:()=>{plannerSelection=null;renderPanel()},planClear:()=>{plannerSelection=[];renderPanel()},planSource:openProductionSource,shopBuy,wardrobeCat:k=>{wardrobeCatId=+k;renderPanel()},outfitColor,outfitSet:equipOutfitSet,premiumFeed:premiumFeedAnimal});
if(typeof initJourney==='function')Object.assign(actions,{
 favoriteGift,memory:claimMemory,customerStory:finishCustomerStory,marketTask:claimMarketTask,marketPrize:buyMarketPrize,marketRecipe:learnFestivalRecipe,valleyProject:restoreValleyProject,
  valleyCrop:k=>{if(TREES[k]){closePanel();World.center();World.placing(k);}else openProductionSource(k);},
  goRiver:()=>{closePanel();World.river();},
 goalGo:goGoal,goalPin:pinGoal,layoutSave:()=>saveFarmLayout($('layoutName')?.value),layoutDelete:deleteFarmLayout,layoutPreview:id=>openPanel('layoutPreview',+id),
 layoutApply:id=>{if(!applyFarmLayout(id))return false;closePanel();return true;},layoutBack:()=>openPanel('layouts'),layoutUndo:undoFarmMove,
 planReserve:reservePlan,planRelease:releaseReservations,planPin:toggleIngredientPin,sellAll:k=>sellItem(k,usableQuantity(k)),
 farmPicture:()=>World.picture(),sound:()=>{S.sound=!S.sound;change();if(typeof FarmAudio!=='undefined')FarmAudio.sync();playTone();}
});
document.addEventListener('input',e=>{if(e.target.id==='barnSearch'){barnQuery=e.target.value.toLowerCase();document.querySelectorAll('[data-barn-name]').forEach(card=>card.hidden=!card.dataset.barnName.includes(barnQuery));}if(e.target.dataset.audio&&S.journey){const k=e.target.dataset.audio;if(['music','ambience','effects'].includes(k)){S.journey.audio[k]=Math.max(0,Math.min(1,+e.target.value/100));saveGame();if(typeof FarmAudio!=='undefined')FarmAudio.sync();}}});
document.addEventListener('click',e=>{const b=e.target.closest('button,[data-open]');if(!b||b.disabled)return;if(activeZone&&(b.dataset.open||b.dataset.action)&&!['exploration','logistics','settings'].includes(b.dataset.open)&&!['visit','trip','tripClaim','cargoFirst','backup','details','effects','waterMotion','sound','farmPicture'].includes(b.dataset.action)){notice('Return to your farm to use this.');return;}if(b.dataset.open)openPanel(b.dataset.open);else if(b.dataset.action){const previousNotice=noticeVersion,result=actions[b.dataset.action]?.(b.dataset.args);if(result===true)playTone();if(result===false&&noticeVersion===previousNotice)notice('Not ready yet. Check coins, ingredients or available cats.');}});
document.addEventListener('change',async e=>{
 if(e.target.id!=='restore')return;const input=e.target,f=input.files[0];if(!f)return;
 try{
  if(f.size>1000000){notice('Backup is too large.');return;}
  const a=JSON.parse(await f.text());if(!validate(a)){notice('This is not a valid MEW HARVEST backup.');return;}
  if(!confirm('Replace this island with the selected backup?'))return;
  S=a;plannerSelection=null;migrateProgression();migrateWardrobe();migrateBaseState();migrateValleyMap();initResources();migrateRiver();initVillage();initLife();
  if(typeof initJourney==='function'){initJourney();layoutUndo=null;catReactions.clear();}
  if(typeof resetProductionNotifications==='function')resetProductionNotifications();if(typeof FarmAudio!=='undefined')FarmAudio.sync();
  World.cancel();World.leaveZone();tick();input.blur?.();change();World.sync(true);notice('Island restored.');
 }catch{notice('This is not a valid MEW HARVEST backup.');}finally{input.value='';}
});
$('leaveZone').onclick=()=>{exitZone();World.leaveZone()};$('close').onclick=closePanel;$('sheet').addEventListener('close',()=>{if(!$('sheet').open)panel=null;});$('farm').onclick=()=>{if(activeZone)return notice('Return to your farm first.');$('seeds').hidden=!$('seeds').hidden;renderSeeds()};$('zoomIn').onclick=()=>World.zoom(1.15);$('zoomOut').onclick=()=>World.zoom(1/1.15);$('center').onclick=()=>World.center();$('cancelPlace').onclick=()=>World.cancel();
onChange=()=>{updateHUD();if(panel)renderPanel();};updateHUD();renderSeeds();
setInterval(()=>{tick();updateHUD();document.querySelectorAll('[data-time]').forEach(el=>el.textContent=remaining(+el.dataset.time));const focused=document.activeElement,holdingButton=focused?.tagName==='BUTTON'&&$('sheet')?.contains(focused);let sig=S.buildings.map(b=>[b.ready<=now(),b.fed&&b.fed<=now(),b.queue.filter(j=>j.end<=now()).length]).join('|')+S.orders.map(o=>o.arrives<=now()).join()+S.resources.map(r=>r.end+':'+r.respawn).join()+'|'+readyGoods()+'|fishing:'+(S.village?.fishing?(S.village.fishing.end<=now()?'ready':'waiting'):'none');if(!holdingButton&&['decoration','craft','resource','exploration','merchant','logistics','village','lifeBuilding'].includes(panel))renderPanel();if(sig!==uiSignature){uiSignature=sig;if(panel&&!holdingButton)renderPanel();}},1000);
window.addEventListener('pagehide',saveGame);
if(navigator&&document.modelContext?.registerTool){try{document.modelContext.registerTool({name:'read_farm',description:'Read this MEW HARVEST farm state without changing it.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({level:level(),coins:S.coins,inventory:{...S.inventory},freeCats:S.cats.filter(c=>!c.job||c.job.end<=now()).length,fields:S.fields.length})});}catch{}}

let audioContext;
function playTone(kind='tap'){if(typeof FarmAudio!=='undefined')return FarmAudio.play(kind);if(!S.sound)return;try{audioContext ||= new (window.AudioContext||window.webkitAudioContext)();audioContext.resume();const o=audioContext.createOscillator(),g=audioContext.createGain();o.connect(g);g.connect(audioContext.destination);o.frequency.setValueAtTime(660,audioContext.currentTime);o.frequency.exponentialRampToValueAtTime(990,audioContext.currentTime+.1);g.gain.setValueAtTime(.04,audioContext.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioContext.currentTime+.18);o.start();o.stop(audioContext.currentTime+.2)}catch{}}

setInterval(()=>{const needle=$('fishNeedle'),f=S.village?.fishing;if(needle&&f&&f.end<=now()){const p=((now()-f.end)%2800)/1400;needle.style.left=((p<=1?p:2-p)*98)+'%';}},70);

window.addEventListener('load',()=>{if(!S.introSeen)openPanel('intro');});
