'use strict';
// Optional fields keep older island backups compatible.
function shopReputation(){const served=S.stats.served,thresholds=[0,10,30,70,140],rank=thresholds.filter(n=>served>=n).length-1;return {rank,name:['New stall','Friendly shop','Village favourite','Market landmark','Five-star market'][rank],bonus:rank*5,next:thresholds[rank+1]||null,served};}
function orderPayment(o){return Math.round(o.reward*(1+(shopReputation().bonus+(typeof customerBonus==='function'?customerBonus(o):0))/100));}
function penUpgradeInfo(b){const n=b.penLevel||0;return {level:n,coins:180*(n+1),need:{plank:4*(n+1),brick:2*(n+1)},seconds:30};}
function upgradePen(id){const b=readyBuilding(+id);if(!b||!BUILDINGS[b.type].animal||b.fed)return false;const d=penUpgradeInfo(b),kit=availableQuantity('maintenance_kit')>0;if(d.level>=2||S.coins<d.coins||(!has(d.need)&&!kit))return false;const cat=assign('Improving animal home',b,now()+d.seconds*1000,'build');if(!cat)return false;S.coins-=d.coins;if(has(d.need))take(d.need);else take({maintenance_kit:1});b.penLevel=d.level+1;b.ready=cat.job.end;change();return true;}
function personalityBenefit(c){return {Curious:'Exploration finds +1',Gentle:'Animal care +5 happiness',Energetic:'Delivery time −10%',Thoughtful:'Cooking time −5%'}[c.personality||PERSONALITIES[c.id%4]];}
function catTrait(c){return c.personality||PERSONALITIES[c.id%4];}
function claimDiscovery(n){n=+n;if(![10,20,35,50].includes(n)||S.village.discovered.length<n||(S.life.discoveryClaims||[]).includes(n))return false;S.life.discoveryClaims ||= [];S.life.discoveryClaims.push(n);S.coins+=n*10;give('bait',3);change();return true;}
function prioritizeCargo(id){const list=S.village.cargo,index=list.findIndex(q=>q.id===+id&&!q.end);if(index<0)return false;list.unshift(list.splice(index,1)[0]);change();return true;}
function farmOverview(){return {crops:S.fields.filter(f=>f.crop&&f.end<=now()).length,pens:S.buildings.filter(b=>b.fed&&b.fed<=now()).length,kitchens:S.buildings.filter(b=>b.queue.some(q=>q.end<=now())).length,life:S.buildings.filter(b=>b.lifeEnd&&b.lifeEnd<=now()).length,waiting:S.village.cargo.filter(q=>!q.end).length,orders:S.orders.filter(o=>o.arrives<=now()&&has(o.need,o.id)).length};}
function nextVillageStep(){if(!S.village.restoration)return {text:'Repair your weathered cottage',panel:'restoration'};if(!S.buildings.some(b=>BUILDINGS[b.type].animal&&b.animals))return {text:'Welcome your first farm animal',panel:'build'};if(!S.stats.served)return {text:'Complete your first customer order',panel:'orders'};if(!S.village.pier)return {text:'Build a fishing pier',panel:'fishing'};const next=Object.entries(BUILDINGS).find(([k,d])=>d.cost>0&&d.level<=level()&&!S.buildings.some(b=>b.type===k));if(next)return {text:'Build '+next[1].name,panel:next[1].life?'villagebuild':'build'};if(!S.life.explored)return {text:'Explore Willow woods',panel:'exploration'};if(S.village.restoration<2)return {text:'Restore your village cottage',panel:'restoration'};const m=VILLAGE_MILESTONES.find(m=>!S.life.milestones.includes(m.id));if(m)return {text:m.name,panel:'progress'};return {text:'Grow your village and complete your discovery book',panel:'collection'};}
function managementPanel(kind){if(kind==='market'){const r=shopReputation();return '<div class="card"><h2>'+r.name+'</h2><p>'+('★'.repeat(r.rank+1))+' · '+r.served+' customers served</p><p>Every order pays '+r.bonus+'% extra coins. '+(r.next?'Next rank at '+r.next+' served customers.':'Highest reputation reached!')+'</p><button data-open="orders">Serve customers</button></div><p class="intro">Every sixth new order is a special delivery with a 25% higher base payment. No cash purchases: all upgrades use farm coins.</p><div class="menu-grid"><button data-open="boutique">Fences, gates & cottages</button><button data-open="supplies">Feed & materials</button><button data-open="villagebuild">Village buildings</button></div>';}
if(kind==='overview'){const s=farmOverview(),n=nextVillageStep();return (awayDuration>=60000?'<p class="intro">Welcome back! You were away '+Math.floor(awayDuration/60000)+' minutes. Your crop and production timers continued.</p>':'')+'<div class="card"><h2>Next on your farm</h2><p>'+n.text+'</p><button data-open="'+n.panel+'">Continue</button></div><div class="grid">'+[['🌾 Crops ready',s.crops,'farm'],['🥚 Animal homes ready',s.pens,'animals'],['🍳 Kitchens ready',s.kitchens,'workshops'],['🌿 Village products ready',s.life,'villagebuild'],['🧺 Waiting deliveries',s.waiting,'logistics'],['🛍 Orders you can serve',s.orders,'orders']].map(([name,count,p])=>'<div class="card"><h2>'+name+'</h2><p>'+count+'</p>'+(p==='farm'?btn('Harvest ready','harvest'):p==='animals'?'<button data-action="animalTab">Open animal homes</button>':'<button data-open="'+p+'">Open</button>')+'</div>').join('')+'</div><div class="card"><h2>Your next unlocks</h2>'+Object.entries(BUILDINGS).filter(([k,d])=>d.level>level()).sort((a,b)=>a[1].level-b[1].level).slice(0,3).map(([k,d])=>'<p>Level '+d.level+' · '+d.name+'</p>').join('')+'</div>';}
return '';}

function startCraft(k){const r=CRAFTS[k];if(!r||!CRAFT_DURATIONS[k]||!has(r.need))return false;const jobs=S.life.crafting||[];if(jobs.length>=3)return false;let start=Math.max(now(),jobs.at(-1)?.end||0),end=start+CRAFT_DURATIONS[k]*1000;let cat=S.cats.find(c=>c.job?.kind==='craft'&&c.job.end>now());if(!cat)cat=assign('Crafting materials',{id:-40,size:2,...S.village.camp},end,'craft');if(!cat)return false;start=Math.max(start,cat.job.workStart||0);end=start+CRAFT_DURATIONS[k]*1000;take(r.need);cat.job.end=end;jobs.push({id:S.nextId++,key:k,start,end,cat:cat.id});S.life.crafting=jobs;change();return true;}
function collectCrafts(){const jobs=S.life.crafting||[],ready=jobs.filter(j=>j.end<=now());if(!ready.length)return false;for(const j of ready){const r=CRAFTS[j.key];queueCargo(r.give,r.count,S.village.camp);}S.life.crafting=jobs.filter(j=>j.end>now());change();return true;}
function craftingPanel(){const jobs=S.life?.crafting||[];return '<div class="card"><h2>Cat crafting bench · '+jobs.length+'/3 slots</h2><p>One cat makes your queued materials at the expedition camp. Collect finished batches, then a helper carries them to the barn.</p>'+jobs.map(j=>'<p>'+CRAFTS[j.key].name+' · '+(j.end<=now()?'Ready':j.start>now()?'Queued':'<span data-time="'+j.end+'">'+remaining(j.end)+'</span>')+'</p>').join('')+btn('Collect finished batches','craftCollect','',!jobs.some(j=>j.end<=now()))+'</div>';}
