'use strict';
function initVillage(){if(!S.village)S.village={rev:1,restoration:S.newVillage?0:1,pier:false,rod:0,fishing:null,fishCaught:0,trips:[],cargo:[],deliveries:0,discovered:[],merchant:{serial:0,arrives:0}};if(!S.village.camp){outer:for(let y=2;y<S.size-2;y++)for(let x=12;x<S.size-2;x++)if(!occupied(x,y,2)){S.village.camp={x,y};break outer;}S.village.camp ||= {x:12,y:3};}for(const c of S.cats){c.personality ||= PERSONALITIES[c.id%4];c.experience ||= 0;c.affection ||= 0;}if(typeof CargoTransport!=='undefined')CargoTransport.init();saveGame();}
initVillage();
Object.assign(CRAFTS,{bait:{name:'Fishing bait ×3',need:{fiber:2,wheat:1},give:'bait',count:3}});
function villageStage(){const score=S.buildings.length+S.parcels.length+S.houseLevel+S.village.deliveries/8;return score<6?'Old farm':score<12?'Growing homestead':score<22?'Cat hamlet':'Harvest village';}
function restoreFarm(){const v=S.village,cost=v.restoration===0?80:400,need=v.restoration===0?{wood:4}:{plank:8,brick:6},kit=v.restoration===0?'builder_toolkit':'repair_kit';if(v.restoration>=2||S.coins<cost||(!has(need)&&!availableQuantity(kit)))return false;S.coins-=cost;if(has(need))take(need);else take({[kit]:1});v.restoration++;change();return true;}
function buildPier(){if(S.village.pier||S.coins<180||(!has({wood:10,rope:2})&&!availableQuantity('boat_supply_kit')))return false;S.coins-=180;if(has({wood:10,rope:2}))take({wood:10,rope:2});else take({boat_supply_kit:1});S.village.pier=true;give('bait',3);change();return true;}
function upgradeRod(){const v=S.village,cost=150*(v.rod+1),need={wood:5,iron:2},kit=availableQuantity('dock_upgrade_parts')>0;if(!v.pier||v.rod>=3||S.coins<cost||(!has(need)&&!kit))return false;S.coins-=cost;if(has(need))take(need);else take({dock_upgrade_parts:1});v.rod++;change();return true;}
function startFishing(baitType='bait'){
 const v=S.village;if(!v.pier||v.fishing||!['bait','premium_bait','special_bait'].includes(baitType)||!availableQuantity(baitType))return false;
 const bait=baitType,hook=availableQuantity('fishing_hook')>0,tackle=quantity('tackle_box')>0;
 const speed=(bait==='premium_bait'?0.8:bait==='special_bait'?0.9:1)*(hook?0.9:1)*(tackle?0.9:1),point=typeof fishingPoint==='function'?fishingPoint():{x:6,y:9.1};
 const c=assign('Fishing',{id:-20,...point,workPoints:[point]},now()+Math.max(10000,(24000-v.rod*4000)*speed),'fish');if(!c)return false;
 take({[bait]:1});if(hook)take({fishing_hook:1});const roll=(v.fishCaught+1)%6;
 v.fishing={cat:c.id,end:c.job.end,item:bait==='special_bait'?'pearl':S.life?.fishSpot==='sea'?(roll%3===0?'pearl':'carp'):S.life?.fishSpot==='pond'?(roll%2===0?'carp':'perch'):roll===0?'pearl':roll%3===0?'carp':'perch',bait,net:availableQuantity('fishing_net')>0};change();return true;
}
function collectFish(){const v=S.village,f=v.fishing;if(!f||f.end>now())return false;let count=f.bait==='premium_bait'?2:1;if(f.net&&availableQuantity('fishing_net')){take({fishing_net:1});count+=2;}if(availableQuantity('fish_bucket')){take({fish_bucket:1});count++;}queueCargo(f.item,count,typeof fishingPoint==='function'?fishingPoint():{x:6,y:8});v.fishCaught++;v.fishing=null;gainXP(5+count);change();return true;}
function startExpedition(k){const d=EXPEDITIONS[k],v=S.village;if(!d||level()<d.level||v.trips.some(t=>!t.claimed&&t.where===k))return false;const map=availableQuantity('explorer_map')>0,compass=availableQuantity('compass')>0,supply=k==='cave'&&availableQuantity('mining_supply_pack')>0,bag=availableQuantity('explorer_bag')>0,basket=availableQuantity('foraging_basket')>0,key=availableQuantity('old_exploration_key')>0,fragment=availableQuantity('treasure_map_piece')>0,lantern=k==='cave'&&availableQuantity('cave_lantern')>0,cost=Math.round(d.cost*(map?0.65:1));if(S.coins<cost)return false;const end=now()+d.time*1000*(compass?0.8:1),c=assign('Exploring '+d.name,{id:-30,size:2,...v.camp},end,'explore');if(!c)return false;for(const item of [map?'explorer_map':null,compass?'compass':null,supply?'mining_supply_pack':null,bag?'explorer_bag':null,basket?'foraging_basket':null,key?'old_exploration_key':null,fragment?'treasure_map_piece':null,lantern?'cave_lantern':null])if(item)take({[item]:1});S.coins-=cost;v.trips.push({id:S.nextId++,where:k,cat:c.id,end:c.job.end,claimed:false,supply,bag,basket,key,fragment,lantern});change();return true;}
function claimExpedition(id){const t=S.village.trips.find(t=>t.id===+id);if(!t||t.claimed||t.end>now())return false;t.claimed=true;for(const[k,n]of Object.entries(EXPEDITIONS[t.where].reward)){let count=n+(t.supply?Math.ceil(n*.5):0)+(t.bag?1:0)+(t.basket&&k==='fiber'?2:0)+(t.key&&k==='pearl'?1:0)+(t.fragment&&k==='gem'?1:0)+(t.lantern&&k==='gem'?1:0);queueCargo(k,count,S.village.camp);}S.village.trips=S.village.trips.filter(t=>!t.claimed);gainXP(10);change();return true;}
function merchantOffer(){const n=S.village.merchant.serial;const pool=['wheat','corn','egg','bread','perch'].filter(k=>canMake(k));const k=pool[n%pool.length]||'wheat';return {need:{[k]:k==='wheat'?8:3},coins:Math.round(ITEMS[k].value*(k==='wheat'?8:3)*2),reward:{wood:4,iron:1}};}
function tradeBoat(){const v=S.village,o=merchantOffer();if(v.merchant.arrives>now()||!has(o.need))return false;take(o.need);S.coins+=o.coins;for(const[k,n]of Object.entries(o.reward))queueCargo(k,n,{x:8,y:12});v.merchant.serial++;v.merchant.arrives=now()+120000;gainXP(12);change();return true;}
function upgradeWorkshop(id){const b=readyBuilding(+id);if(!b||['house','store'].includes(b.type)||BUILDINGS[b.type].animal||b.queue.length||b.lifeEnd||(b.upgrade||0)>=2)return false;const cost=300*((b.upgrade||0)+1),need={plank:4,brick:3},kit=availableQuantity('workshop_upgrade_kit')>0;if(S.coins<cost||(!has(need)&&!kit))return false;const c=assign('Upgrading',b,now()+20000,'build');if(!c)return false;S.coins-=cost;if(has(need))take(need);else take({workshop_upgrade_kit:1});b.upgrade=(b.upgrade||0)+1;b.ready=c.job.end;change();return true;}
function petCat(id){const c=S.cats.find(c=>c.id===+id);if(!c||c.petted===day())return false;c.petted=day();c.affection=Math.min(100,(c.affection||0)+10);change();gameNotice(c.name+': Prrr! Thanks for looking after me.');return true;}
function queueCargo(item,count,from){if(!ITEMS[item]||count<1)return;const v=S.village,existing=v.cargo.find(q=>!q.end&&q.item===item&&q.x===from.x&&q.y===from.y);if(existing){existing.count+=count;return;}v.cargo.push({id:S.nextId++,item,count,x:from.x,y:from.y,start:0,end:0,cat:null});}
function villageTick(){const v=S.village;let dirty=false;
 for(const q of v.cargo){if(q.end&&q.end<=now()&&!q.done){
  give(q.item,q.count);if(!v.discovered.includes(q.item))v.discovered.push(q.item);v.deliveries++;q.done=true;
  if(typeof CargoTransport!=='undefined')CargoTransport.finish(q);
  const c=S.cats.find(c=>c.id===q.cat),store=S.buildings.find(b=>b.type==='store');
  if(c&&c.job?.cargo===q.id){c.experience=(c.experience||0)+1;const destination=q.route?.points.at(-1)||{x:store.x+2.1,y:store.y+1};c.x=destination.x;c.y=destination.y;c.job.x=c.x;c.job.y=c.y;if(typeof World!=='undefined'&&World.arriveDelivery)World.arriveDelivery(c);c.job=null;}
  dirty=true;
 }}
 v.cargo=v.cargo.filter(q=>!q.done);
 for(const q of v.cargo){if(q.end)continue;
  const store=S.buildings.find(b=>b.type==='store');if(!store)continue;
  const end=now()+Math.max(15000,(Math.abs(q.x-store.x)+Math.abs(q.y-store.y)+20)*600),c=assignQuiet(q,end);if(!c)break;
  q.cat=c.id;q.start=now();q.end=c.job.end;
  if(typeof bondSpeed==='function'){q.end=now()+(q.end-now())*bondSpeed(c);c.job.end=q.end;}
  if(typeof World!=='undefined'&&World.deliveryPlan){
   if(typeof CargoTransport!=='undefined')CargoTransport.reserve(q);
   let route=World.deliveryPlan(q,c);
   // A vehicle never takes a ferry or drives through water. Foot delivery
   // remains available when a narrow/blocked route cannot reach the tractor.
   if(!route&&q.vehicle==='tractor'){delete q.vehicle;route=World.deliveryPlan(q,c);}
   if(!route){c.job=null;q.start=0;q.end=0;q.cat=null;delete q.vehicle;q.blocked=true;dirty=true;continue;}
   q.blocked=false;q.route=route;q.end=now()+Math.max(5000,route.distance*650)*(catTrait(c)==='Energetic'?.9:1)*(typeof bondSpeed==='function'?bondSpeed(c):1);c.job.end=q.end;
   if(typeof CargoTransport!=='undefined')CargoTransport.configure(q,c);
  }dirty=true;
 }if(dirty)change();}
function assignQuiet(q,end){const c=S.cats.find(c=>(!c.job||c.job.end<=now())&&c.role==='haul')||freeCat();if(!c)return null;c.job={label:'Delivering '+ITEMS[q.item].name,target:q.id,x:q.x+.5,y:q.y+.8,end:typeof catTrait==='function'&&catTrait(c)==='Energetic'?now()+(end-now())*.9:end,kind:'haul',cargo:q.id};return c;}
function villagePanel(kind){const v=S.village;
if(kind==='village')return '<p class="intro">'+villageStage()+' · '+v.deliveries+' deliveries completed</p><div class="menu-grid">'+[['chapters','📖 Village story'],['friends','💛 Cat friendships'],['cookbook','🍽 Recipe book'],['mountain','⛰ Willow mountain'],['overview','📋 Farm overview'],['market','⭐ Shop reputation'],['progress','🏆 Village progress'],['villagebuild','🏡 Village buildings'],['workboard','📋 Work board'],['tools','🛠 Tools & compost'],['interior','🛏 Cottage interior'],['festival','🎪 Village festival'],['collection','📖 Discoveries'],['fishing','🎣 River fishing'],['exploration','🧭 Explore'],['merchant','⛵ Merchant boat'],['logistics','🧺 Deliveries'],['restoration','🏡 Restore farm'],['crew','🐱 Cat characters']].map(([k,n])=>'<button data-open="'+k+'">'+n+'</button>').join('')+'</div><div class="card"><h2>Your growing village</h2><p>'+S.cats.length+' cats · '+S.buildings.length+' buildings · '+S.parcels.length+' meadow plots</p><p>Plant crops, raise animals, cook, gather materials and deliver goods to grow your village.</p></div>';
if(kind==='restoration'){const cost=v.restoration===0?80:400,need=v.restoration===0?{wood:4}:{plank:8,brick:6},kit=v.restoration===0?'builder_toolkit':'repair_kit';return '<div class="card"><img class="portrait" src="art/village-'+(v.restoration===0?2:3)+'.webp" alt=""><h2>'+['Weathered cottage','Restored homestead','Village cottage'][v.restoration]+'</h2><p>Repair the old cottage, then add a balcony and village garden.</p><p>'+needs(need)+' · or 1 '+ITEMS[kit].name+'</p>'+btn(v.restoration>=2?'Fully restored':'Restore · 🪙 '+cost,'restoreFarm','',v.restoration>=2||S.coins<cost||!has(need)&&!availableQuantity(kit))+'</div><button data-open="supplies">Buy materials</button>';}
 if(kind==='fishing'){
  if(!v.pier)return '<div class="card"><h2>Build a fishing pier</h2><p>'+needs({wood:10,rope:2})+' · or use a Boat Supply Kit</p>'+btn('Build · 🪙 180','pier','',S.coins<180||!has({wood:10,rope:2})&&!availableQuantity('boat_supply_kit'))+'<p>Includes 3 bait. Craft more in Craft & forest.</p></div>';
  return '<div class="tabs">'+['river','pond','sea'].map(k=>btn((S.life?.fishSpot||'river')===k?'✓ '+k:k,'fishSpot',k,!!v.fishing||k==='pond'&&!S.buildings.some(b=>b.type==='ducks'&&b.ready<=now())||k==='sea'&&(S.life?.explored||0)<6,true)).join('')+'</div><p class="intro">Pond unlocks with a duck pond. Sea unlocks after 6 exploration finds. Premium bait catches two fish; special bait favours rare catches.</p>'+
   '<div class="card"><h2>Fishing · Rod '+(v.rod+1)+'</h2><p>Available bait: '+availableQuantity('bait')+' · Premium: '+availableQuantity('premium_bait')+' · Special: '+availableQuantity('special_bait')+' · Fish caught: '+v.fishCaught+'</p>'+
   (v.fishing?'<p>Waiting for a bite · <span data-time="'+v.fishing.end+'">'+remaining(v.fishing.end)+'</span></p>'+(v.fishing.end<=now()?'<div class="fish-meter"><i id="fishNeedle"></i></div><p>Reel when the marker is in green for a bonus catch.</p>':'')+btn('Reel in catch','fishCollect','',v.fishing.end>now()):'<div class="tabs">'+[['bait','basic'],['premium_bait','premium'],['special_bait','special']].map(([key,label])=>btn('Cast · '+label+' bait','fish',key,!availableQuantity(key)||!freeCat(),true)).join('')+'</div>')+
   ' '+btn('Go to pier','goPier','',false,true)+'</div><div class="card"><h2>Upgrade rod</h2><p>'+needs({wood:5,iron:2})+' · or 1 Dock Upgrade Parts</p>'+btn(v.rod>=3?'Fully upgraded':'Upgrade · 🪙 '+150*(v.rod+1),'rod','',v.rod>=3||S.coins<150*(v.rod+1)||!has({wood:5,iron:2})&&!availableQuantity('dock_upgrade_parts'))+'</div><button data-open="craft">Craft bait</button>';
 }
if(kind==='exploration')return '<p class="intro">Visit an area and tap resources to gather them yourself, or send a cat on a timed supply trip.</p>'+Object.entries(EXPEDITIONS).map(([k,d])=>{const t=v.trips.find(t=>t.where===k&&!t.claimed);return '<div class="card"><h2>'+d.name+'</h2>'+btn('Visit & explore','visit',k,level()<d.level||!freeCat())+'<p>'+Object.entries(d.reward).map(([k,n])=>ITEMS[k].name+' ×'+n).join(' · ')+'</p>'+(t?'<p>Returns in <span data-time="'+t.end+'">'+remaining(t.end)+'</span></p>'+btn('Collect finds','tripClaim',t.id,t.end>now()):btn(level()<d.level?'Level '+d.level:'Explore · 🪙 '+d.cost+' · '+d.time+'s','trip',k,level()<d.level||S.coins<d.cost||!freeCat()))+'</div>';}).join('');
if(kind==='merchant'){const o=merchantOffer();return '<div class="card"><h2>Merchant boat</h2><p>'+needs(o.need)+'</p><p>Earn 🪙 '+o.coins+' + 4 wood + 1 iron</p>'+(v.merchant.arrives>now()?'<p>Next boat in <span data-time="'+v.merchant.arrives+'">'+remaining(v.merchant.arrives)+'</span></p>':'')+btn('Load & trade','boat','',v.merchant.arrives>now()||!has(o.need))+'</div>';}
if(kind==='logistics')return (typeof CargoTransport!=='undefined'?CargoTransport.panel():'')+'<p class="intro">Harvested goods wait at their source. Free cats carry them to the store, then they enter your barn. '+v.deliveries+' deliveries completed.</p>'+v.cargo.map(q=>'<div class="card"><h2>'+ITEMS[q.item].icon+' '+ITEMS[q.item].name+' ×'+q.count+'</h2><p>'+(q.end?(q.vehicle==='tractor'&&typeof CargoTransport!=='undefined'?CargoTransport.label(q):'On the way')+' · <span data-time="'+q.end+'">'+remaining(q.end)+'</span>':q.blocked?'Route blocked. Move fences or clear access to the store.':'Waiting for a free cat')+'</p>'+(!q.end?btn('Deliver next','cargoFirst',q.id,false,true):'')+'</div>').join('')+(!v.cargo.length?'<p>All goods delivered.</p>':'');return '';}
